### ISSUE TITLE
Add @Deprecated Tag to deprecated methods

### ISSUE THREAD

**Issue by Superharz** [LWJGL/lwjgl3#119]
It would be nice to add @Deprecated Tags to deprecated methods so that an IDE like NetBeans can cross these methods out
<ul>
 <li>Faster identification of these methods</li>
</ul>

**Comment by Spasi** [comment]
If you mean OpenGL functions that are not available in the Core Profile, making them `@Deprecated` would be very annoying for legacy applications or applications that use the Compatibility Profile. There are no easy replacements for such functions, you'd have to rewrite major parts of a renderer to get rid of them.

**Comment by Superharz** [comment]
However, it would be easier for new Users to see which functions should not be used
<ul>
 <li>If you want to make an application using the latest stuff</li>
</ul>

**Comment by Spasi** [comment]
For new development it's easy, just use a Core Profile context. If that is not desired (there's a performance hit due to extra validation), LWJGL supports a pseudo-forward-compatible mode that you can enable with:

`GL.createCapabilities(true);`

This will make LWJGL not load pointers for deprecated functions, so you'll get an exception if they are used by mistake. Deprecated constants (e.g. `GL_QUADS`) will continue to work though.

**Comment by Superharz** [comment]
Alright, you win :smile: 
My only idea was, that you could spot these functions more easy with an IDE like NetBeans, but your way is better

**Comment by httpdigest** [comment]
> GL.createCapabilities(true);

That's interesting. In this case it might be desirable to not force the user to specify to LWJGL that those functions should not be loaded because they would not be available anyways (i.e. lead to GL errors) when using a forward compatible context. Instead one could let LWJGL know that such a context was requested.
Either by intercepting the GLFW context window attributes or in the case of SWT have its context creation function notify LWJGL about it.

What do you think?

**Comment by Spasi** [comment]
> Or another way would be to let GL.createCapabilities figure it out itself whether the active GL context is a forward compatible one. However that would only be possible when using a >= 3.2 context.

It works [like that](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/main/java/org/lwjgl/opengl/GL.java#L331) already. The `forwardCompatible` parameter of `GL.createCapabilities` is useful only when working with legacy/compatibility profile contexts.

**Comment by httpdigest** [comment]
Okay, that's how I would've done it too, though interestingly this does not work (at least) on the 354.42 Nvidia driver.
Even when requesting forward compatibility with WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB context flag, the glGetInteger query only returns 1 (for core context).
