### ISSUE TITLE
Trying to use lwjgl with Eclipse on OSX 10.11

### ISSUE THREAD

**Issue by NozzyEz** [LWJGL/lwjgl3#132]
trying to run this code: http://pastebin.com/tfJwpibZ
and I get this error:
<img width="814" alt="screen shot 2016-01-15 at 15 07 06" src="https://cloud.githubusercontent.com/assets/16720471/12354945/ab8413c6-bb99-11e5-8322-8a44feab80cd.png">

I did make the getting started code to run by applying -XstartOnFirstThread

but this code keeps not wanting to run, I am fairly green with Java, meaning I've programmed basic stuff with it for a while, but never anything to this extend. therefore I am at a loss.

**Comment by httpdigest** [comment]
The error message is plain and clear: "GLFW windows may only be created on the **main** thread"
The main thread is the thread that runs your `public static main(String[] args)` method.
You however immediately spawn a new Thread in which you do everything.
Don't do that. :)
Simply run all your code on the main thread and don't spawn a new Thread.

**Comment by NozzyEz** [comment]
Obviously... I feel ashamed I didn't see that.... I didn't come up with the code, but I typed it in so I should have realized. I commented it out, and also made a call to run() (How the code is supposed to work without it I don't know?) 

long story short, it works, although I expected an all black window, it seems to be flashing rapidly...

**Comment by httpdigest** [comment]
The flashing is likely because you don't actually render anything and the backbuffer contains garbage. You should at least `GL11.glClear(GL11.GL_COLOR_BUFFER_BIT)` the backbuffer before swapping buffers. But for this you must also initialize LWJGL properly. See the [getting started](https://www.lwjgl.org/guide) guide again for how to do that.
That `run` method comes from the `java.lang.Runnable` interface, because your class `implements` that. That can be removed. It was needed in order for the spawned Thread to execute.
