### ISSUE TITLE
VAO's not shared when creating windows with shared contexts

### ISSUE THREAD

**Issue by rreleford** [LWJGL/lwjgl3#157]
Passing window id of "main window" to the createWindow method of secondary window but still get memory access violations when trying to render a vao created in the first windows context with drawelements.

**Comment by ppiastucki** [comment]
https://www.opengl.org/registry/specs/ARB/vertex_array_object.txt
explicitly states that: "It also differs in that vertex array objects are explicitly not sharable between contexts."   
You need to create and use VAOs in the same context.

**Comment by httpdigest** [comment]
In OpenGL _only_ those OpenGL objects can be shared which are not container objects and which hold data on the server-side/graphics card. This means that, like @ppiastucki said, VAOs are not shared because it is a container object and references other objects. This also means that in OpenGL 3.0+ FBOs are not shared.
See: https://www.opengl.org/wiki/OpenGL_Object#Object_Sharing

**Comment by rreleford** [comment]
@ppiastucki  @httpdigest  Thank you both for the quick replies and helpful links.
