### ISSUE TITLE
Nightly build does not include 32 bit linux native .so files

### ISSUE THREAD

**Issue by Kingwad** [LWJGL/lwjgl3#162]
The native folder from the nightly release from March 24 2016 does not include the following files:

libglfw32.so
libjemalloc32.so
liblwjgl32.so
libopenal32.so

and so does not support 32-bit Linux systems. The 32-bit dll files for Windows are included.

**Comment by Spasi** [comment]
Support for Linux x86 [has been dropped](http://forum.lwjgl.org/index.php?topic=6086.0).

If someone contributes travis build scripts that work (for LWJGL and all its dependencies) and also maintains them, I don't have a problem with restoring support for Linux x86.

Btw, there's far more interest for ARM builds, so that has priority right now.

**Comment by Zomnut** [comment]
Where are the Travis build scripts located currently?

**Comment by Spasi** [comment]
At the [LWJGL-CI](https://github.com/LWJGL-CI?tab=repositories) account:

- There are forks for LWJGL and each dependency.
- Each fork has a branch for each platform/arch.
- Each branch is being continuously rebased to the latest commit, with a single commit on top that adds the travis build script. (you don't need to worry about that, it's being handled by our [teamcity server](http://teamcity.lwjgl.org/))

Some of these are trivial to build on x86, others are painful. You can ignore the aws stuff.

**Comment by coreybruce** [comment]
Debian, Arch32, Gentoo etc still support 32bit and have the native libraries there. I have Arch32 on a old laptop for example and it can use the latest java 17
