### ISSUE TITLE
WGL not instantiable anymore

### ISSUE THREAD

**Issue by httpdigest** [LWJGL/lwjgl3#171]
The class `org.lwjgl.opengl.WGL` has no constructor anymore to instantiate it via:
```Java
new WGL(gl = GL.getFunctionProvider())
```

I need to call WGL functions without having an OpenGL context current to create a context with the Windows platform API.
See: https://github.com/httpdigest/lwjgl3-swt/blob/master/src/org/lwjgl/opengl/swt/PlatformWin32GLCanvas.java

Is there another possibility to call into WGL without instantiating LWJGL and the capabilities?

**Comment by Spasi** [comment]
The binding classes cannot be instantiated anymore and all function addresses have been moved to the capabilities classes. This was part (22e8f34dbcbcbf526ef02fc1db11e063271ae4b8) of the recent function calling optimizations.

This issue is partially fixed by 364b881cc138f2cf8ef8d8d8818ea93d7fad5249.

The plan is to make all GLX & WGL extensions usable without a current context. I'll add `GLXCapabilities` and `WGLCapabilities` classes and all platform-specific extensions will be removed from `GLCapabilities`.
