### ISSUE TITLE
Missing alBufferData with byte[]

### ISSUE THREAD

**Issue by Wolftein** [LWJGL/lwjgl3#193]
Currently there is a alBufferData for short[], int[] and float[] but not for byte[]

**Comment by Spasi** [comment]
This is intentional. Two reasons:

- Generating `byte[]` overloads were applicable would add many (100s) new methods, resulting in API bloat.
- Array parameters were added so that **computations** could happen on an array, which is then passed to native code **without a copy**. Byte data is very rarely involved in computations.

Using `alBufferData` as an example, usually you load an uncompressed audio file or decode a compressed one to a buffer, then pass that buffer to `alBufferData`. No Java computation is going on. Using `byte[]` here instead of `ByteBuffer` provides no benefit. You'd already use a `ByteBuffer` anyway when loading a file (via NIO) or decoding (via stb_vorbis for example).

Another problem with low-frequency functions like `alBufferData`: LWJGL generates JNI [Critical Natives](http://stackoverflow.com/questions/36298111/is-it-possible-to-use-sun-misc-unsafe-to-call-c-functions-without-jni/36309652#36309652) for methods with array parameters. The critical path is only enabled after the method is JIT compiled, which on a modern JVM only happens after it has been called many times (on `-server` the default `CompileThreshold` is 10000). So, in normal use, methods like `alBufferData` would very likely be interpreted and non-critical on the native side, which means an extra copy for your data. And the data passed to *BufferData/TexImage/etc is usually big.

An example where array parameters are useful: Computing a 4x4 matrix and loading it to a shader uniform.
