### ISSUE TITLE
Generator Doubts

### ISSUE THREAD

**Issue by J-Ibarra** [LWJGL/lwjgl3#195]
Hello, the reason for this issue is for questions about the current lwjgl because I have doubts and I would like to help me to contribute to the project in the future!

Reading the code repository to understand the generator, but I still have doubts hope someone can help me without me behind in the work they do!

First: For use language Kotlin then generate the * .java ? Comfort? Speed? Standardization?

Second : In the build.xml ant file downloading native libraries as * .dll , * .so and * respectively .dylib seen in this part of targue

<target name="release" description="Creates the LWJGL binary redistributable" depends="compile,javadoc,-build-version">

Why libraries are downloaded and files are not generated * .c * .h and then be compiled ?

Third: As used * .h files found in lwjgl3 \ modules \ core \ src \ main \ include since I do not watch * .c files

Well that's all for now, I hope it's not some discomfort for developers and are available to answer questions I see that many have.
When you have the ability to assist in the project I would work on integrating a physics engine to lwjgl either bullet physics , physx or some other point in the community discussions
Thank you very much and sorry for the inconvenience

if I caused any discomfort excuse is not my intention , I just want to learn

sorry for my English

**Comment by Spasi** [comment]
> First: For use language Kotlin then generate the * .java ? Comfort? Speed? Standardization?

The code generator and the binding templates are written in Kotlin. Reasons:

- The generator is incredibly complex and a higher-level (than Java) language helps with making the code easier to understand and maintain.
- Kotlin enables the definition of a DSL-like API for the templates. This makes the templates much more compact, cleaner and enables an extra level of type safety. LWJGL 2 used Java interfaces + annotations for this and it was a bad experience.
- Kotlin supports multi-line strings and string interpolation which helps a lot when adding documentation to the bindings.

With that said, Kotlin is only used offline to generate code. You don't have to know Kotlin to use LWJGL and there's no runtime dependency to the Kotlin runtime.

> Second : In the build.xml ant file downloading native libraries as * .dll , * .so and * respectively .dylib seen in this part of targue
>
> Why libraries are downloaded and files are not generated * .c * .h and then be compiled ?

Binaries are never committed to the LWJGL repository, it's a bad practice. LWJGL downloads:

- Static library dependencies (.lib and .a files), as part of the native compilation process.
- Misc resources (images, fonts, sounds), for running the tests and demos.
- Shared libraries (.dll, .so, .dylib files), as part of the release process.

The third one is the one in build.xml that you mention. It's there because LWJGL is cross-platform and you cannot build all binaries in the same system in order to do a release.

> Third: As used * .h files found in lwjgl3 \ modules \ core \ src \ main \ include since I do not watch * .c files

Some of those are single-header libraries. Others are definitions LWJGL needs for statically linked libraries. Not everything requires a corresponding .c file and that's normal. I can provide more information if you'd like to ask about a particular binding.

**Comment by J-Ibarra** [comment]
Thank you so much! I will continue reading and studying the form generator used in this project, I'll take a project in C and try to do the generator and JNI on Kotlin similar to LWJGL way, and thought of USB HID communication and serial communicatiThank you so much! I will continue reading and studying the form generator used in this project, I'll take a project in C and try to do the generator NYI Kotlin similar to LWJGL way, and thought of USB HID communication and serial communication for micro and pic's, because I use it a lot every day! I hope to learn a lot more and thus help direct the project, then I am very excited, thank you very much, if you have something to add, as references, books, links, videos, or some source to help be grateful!on because I use it a lot every day! I hope to learn a lot more and thus help direct the project, then I am very excited, thank you very much, if you have something to add, as references, books, links, videos, or some source to help be grateful!
