### ISSUE TITLE
Vulkan vkGetDeviceQueue EXCEPTION_ACCESS_VIOLATION

### ISSUE THREAD

**Issue by gijswl** [LWJGL/lwjgl3#207]
When my program calls vkGetDeviceQueue after initializing the VkInstance, VkPhysicalDevice and VkDevice it exits the JVM with an EXCEPTION_ACCESS_VIOLATION at address 0x0000000000000000.
It may be due to a mistake on my side, but with the research I've done I believe it is because VkDeviceQueueCreateInfo.npQueuePriorities(struct, value) calls nqueueCount(struct, value.remaining()) instead of nqueueCount(struct, value.capacity()). Causing the queueIndex of vkGetDeviceQueue to be out of range, resulting in the memory access at NULL (0x0).
The same goes for VkDeviceCreateInfo.npQueueCreateInfos and nqueueCreateInfoCount

I hope someone can confirm this, I'm using LWJGL 3.0.0 build 90

**Comment by Spasi** [comment]
LWJGL uses `.remaining()` in all methods and struct setters. Why would `.capacity()` be used instead of `.remaining()`?

Could you share the code you use to initialize the `VkDevice`?

For a working Vulkan demo using LWJGL, see the [HelloVulkan](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/vulkan/HelloVulkan.java) sample.

**Comment by gijswl** [comment]
I thought .capacity() would be used because the C++ tutorial (https://vulkan-tutorial.com) i was following did that.

                int queueFamily = getQueueFamily(physicalDevice);
		VkDeviceQueueCreateInfo.Buffer queueCreateInfos = VkDeviceQueueCreateInfo.create(1);

		FloatBuffer priorities = BufferUtils.createFloatBuffer(1);
		priorities.put(1.0f);
		
		VkDeviceQueueCreateInfo queueCreateInfo = new VkDeviceQueueCreateInfo(BufferUtils.createByteBuffer(VkDeviceQueueCreateInfo.SIZEOF));
		queueCreateInfo.sType(VK10.VK_STRUCTURE_TYPE_DEVICE_QUEUE_CREATE_INFO);
		queueCreateInfo.queueFamilyIndex(queueFamily);
		queueCreateInfo.pQueuePriorities(priorities);
		queueCreateInfos.put(queueCreateInfo);

		VkDeviceCreateInfo createInfo = new VkDeviceCreateInfo(BufferUtils.createByteBuffer(VkDeviceCreateInfo.SIZEOF));
		createInfo.sType(VK10.VK_STRUCTURE_TYPE_DEVICE_CREATE_INFO);
		createInfo.pQueueCreateInfos(queueCreateInfos);
		
		PointerBuffer pDevice = BufferUtils.createPointerBuffer(1);
		if (VK10.vkCreateDevice(physicalDevice, createInfo, null, pDevice) != VK10.VK_SUCCESS) {
			throw new RuntimeException("Failed to create logical device");
		} else {
			logicalDevice = new VkDevice(pDevice.get(), physicalDevice, createInfo);
		}

**Comment by Spasi** [comment]
OK, I see the problem. First of all, LWJGL is consistent with typical NIO code: When you pass a NIO buffer to a method, the method consumes (reads from or writes to) the part of the buffer between `position()` and `limit()`. In this example, when calling:

```java
queueCreateInfo.pQueuePriorities(priorities);
```

LWJGL will use the current `priorities.position()` (**not** the start of the buffer) to set the `pQueuePriorities` pointer and `priorities.remaining()` to set the `queueCount` value. The remaining number of elements is `limit - position`, which is exactly how typical NIO code behaves.

So, you have two options:

a) Use **relative** `put` calls when filling the buffer, then `flip()` the buffer before passing it to the consuming method, or
b) Use **absolute** `put` calls when filling the buffer, so that `position()` never changes.

LWJGL recommends the later, it makes the code shorter and easier to understand. See _Strategy 2_ in [Memory management in LWJGL 3](http://blog.lwjgl.org/memory-management-in-lwjgl-3/) for more information.

**Comment by gijswl** [comment]
Ah I see, it works now. Thanks for the help

**Comment by FexyFex** [comment]
I know it's been 3 years but I just wanted to say that this thread right here saved me from going completely insane. I love you people.
