### ISSUE TITLE
OpenAL alcMakeContextCurrent error ?

### ISSUE THREAD

**Issue by DeepSnowNeeL** [LWJGL/lwjgl3#219]
Not sure if it's me or I am missing something,
I have a weird AL10.alGetError() state stuck on 40964,  AL_INVALID_OPERATION the requested operation is not valid, when trying to destroy the context.
Here is a minimal test case with the problem :

```java
long device = ALC10.alcOpenDevice((ByteBuffer) null);
ALCCapabilities deviceCaps = ALC.createCapabilities(device);
long context = ALC10.alcCreateContext(device, (IntBuffer) null);
ALC10.alcMakeContextCurrent(context);
AL.createCapabilities(deviceCaps);

int error = AL10.alGetError();
if (error != AL10.AL_NO_ERROR) {
	System.err.println("OpenAL Error 1 " + error);
}

System.out.println(context + " is the current context");

//I put 0 to mean NULL, not sure about that but can't pass anything else as it takes a long
boolean test = ALC10.alcMakeContextCurrent(0);
if (!test)
	System.err.println("error alcMakeContextCurrent");

System.out.println(context + " is the current context");

ALC10.alcDestroyContext(context);
error = AL10.alGetError();
if (error != AL10.AL_NO_ERROR) {
	System.err.println("OpenAL Error 2 " + error);
}
ALC10.alcCloseDevice(device);
error = AL10.alGetError();
if (error != AL10.AL_NO_ERROR) {
	System.err.println("OpenAL Error 3 " + error);
}
```

It produces the following output:

> 6375408 is the current context
> 6375408 is the current context
> OpenAL Error 2 40964
> OpenAL Error 3 40964

but it seems to do the job since I have no error message like `AL lib: (EE) alc_cleanup: 1 device not closed`
I'm using lwjgl 3.0.0

**Comment by Spasi** [comment]
> I have a weird AL10.alGetError() state stuck on 40964, AL_INVALID_OPERATION the requested operation is not valid, when trying to destroy the context.

The `alGetError` function is an AL function. It can only be called within an active OpenAL context, that's why you're getting an `INVALID_OPERATION` error. If you switch to `ALC10.alcGetError` the errors will go away, your cleanup code works fine.

> I put 0 to mean NULL, not sure about that but can't pass anything else as it takes a long

LWJGL defines a `NULL` constant in the `MemoryUtil` class. When used with static imports (the recommended style), code becomes like `boolean test = alcMakeContextCurrent(NULL);`, which is clean and easily understandable.

> System.out.println(context + " is the current context");

The second time this is called it should probably be changed to `System.out.println(alcGetCurrentContext() + " is the current context");`

**Comment by DeepSnowNeeL** [comment]
Allright my bad then, couldn't find the information about alGetError only working with an active context !
Thanks for the help ! And thanks for the lib :)
