### ISSUE TITLE
Vulkan Bindings: missing setter in VkDeviceQueueCreateInfo

### ISSUE THREAD

**Issue by JulianKunze** [LWJGL/lwjgl3#223]
Just a quick heads up that the setter for the value of _queueCount_ is missing from the _VkDeviceQueueCreateInfo_ struct. 
It is possible to set this value with the _nqueueCount_ version.

**Comment by Spasi** [comment]
> the setter for the value of queueCount is missing from the VkDeviceQueueCreateInfo struct. 

This is by design. Note that the spec says: 

> `pQueuePriorities` *must* be a pointer to an array of `queueCount` float values

The `queueCount` field is set to `.remaining()` of the buffer you pass to `pQueuePriorities`. This simplifies code when populating struct members. It is equivalent to hiding count/length parameters in functions, when the count/length can be derived from a buffer parameter (using its `.remaining()` value).

> It is possible to set this value with the nqueueCount version.

This is consistent with the unsafe method overloads (prefixed with an `n`) in LWJGL bindings; if you find the default behavior problematic, there's always a way to override it and implement custom solutions.

**Comment by JulianKunze** [comment]
I see, sorry for the false assumption and thanks for the explanation.
