### ISSUE TITLE
APITrace doesn't attach to LWJGL applications

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#232]
Application: https://github.com/kenzierocks/APITraceTest
Run `./gradlew installDist` to prepare the application. Run the app like so: `<apitrace> trace -v -a gl ./build/install/APITraceTest/bin/APITraceTest`.
You'll notice that apitrace will not attach to the program or generate a trace. I'm not sure why, but I suspect LWJGL is not loading the apitrace wrapper OpenGL library. However, I don't know how to make that happen.

I've run apitrace on a regular C OpenGL application just fine.

**Comment by Spasi** [comment]
You can make LWJGL load the apitrace wrapper using the `Configuration.OPENGL_LIBRARY_NAME` option (or the `-Dorg.lwjgl.opengl.libname` system property).

The problem is GLFW though, it also loads the OpenGL library and there may be trouble if LWJGL uses another one. So, depending on your OS, you'll also have to use the workarounds described [here](https://github.com/apitrace/apitrace/blob/master/docs/USAGE.markdown), under *Tracing Manually*.

**Comment by kenzierocks** [comment]
Ok, that works well. I'm currently trying to track down a mysterious `INVALID_OPERATION` that only appears if I check errors *more often*, which is very curious.

**Comment by Spasi** [comment]
Have you tried using a debug context? Use `glfwWindowHint(GLFW_OPENGL_DEBUG_CONTEXT, GLFW_TRUE)` and call `GLUtil.setupDebugMessageCallback()` after `GL.createCapabilities()`.

**Comment by kenzierocks** [comment]
It looks like there's no support for that on OSX: My OpenGL version only goes up to 4.1 and none of the extensions are available.
