### ISSUE TITLE
Crash on vkBindImageMemory in examples

### ISSUE THREAD

**Issue by ShchAlexander** [LWJGL/lwjgl3#238]
I'm trying to run **TwoRotatingTrianglesDemo** and almostly every time it is crashes on 675 line on _vkBindImageMemory_ call. 

* **OS:** Win 10 x64 v1511 build 10586.164 
* **Videocard:** MSI GeForce GTX 1060 Armor 6G
* **Driver:** Nvidia 372.70 08/30/2016

[hs_err_pid5684.zip](https://github.com/LWJGL/lwjgl3/files/481197/hs_err_pid5684.zip)
[vulkaninfo.txt](https://github.com/LWJGL/lwjgl3/files/481202/vulkaninfo.txt)

**Comment by httpdigest** [comment]
Thanks for reporting! This was indeed a bug in the demo.
Should be fixed by https://github.com/LWJGL/lwjgl3-demos/commit/ae5added4bf731b67f74ed629d7b01d39d58423e.
Though this issue should've been posted to the lwjgl3-demos repository. Probably, @Spasi can move it there.

**Comment by ShchAlexander** [comment]
Thank you! :)

**Comment by httpdigest** [comment]
I just noticed that the style of memory allocations done in these demos is now rather discouraged. Instead of manually allocating and freeing the NIO buffers, better use the MemoryStack with the try-with-resources statement.
See the [HelloWorld](https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/test/java/org/lwjgl/demo/vulkan/HelloVulkan.java#L359) demo in the lwjgl3 repository.
