### ISSUE TITLE
LWJGL 3.1.0 Platform Natives on Maven

### ISSUE THREAD

**Issue by hyfloac** [LWJGL/lwjgl3#256]
The [downloader page for LWJGL3](https://www.lwjgl.org/download) has a an option for Gradle and Maven which both delegate their downloads to `Maven Central`, there is a minor problem because the [libraries on maven for `lwjgl-platform`](https://mvnrepository.com/artifact/org.lwjgl/lwjgl-platform) are outdated (version `3.0.0`) while native version do exist for version `3.1.0` (they can be found at the bottom of the [download page](https://www.lwjgl.org/download) hidden behind the button `Click to browse...` which seems to integrate with `https://build.lwjgl.org/release/3.1.0/**OS**/**ARCHITECTURE**/lib**LIBRARY**.**EXT**` (imagine that markdown was working inside code blocks)). The libraries are definitely different versions (some of the newer ones are smaller (`liblwjgl.dylib` is ~500KB smaller in `3.1.0`). If someone could upload the latest natives to Maven that would be extremely useful (I believe my project is crashing due to out of date natives).

**Comment by Spasi** [comment]
There is no problem with the libraries on Maven Central. LWJGL was refactored in version `3.1.0` to have a [modular structure](https://github.com/LWJGL/lwjgl3/issues/100). There have been significant changes because of that.

- The LWJGL core and each binding is a separate artifact.
- There is no `lwjgl-platform` artifact in `3.1.0` or higher. The native libraries are available as a separate artifact for the LWJGL core and each binding (same name, different classifiers).
- The core native library is indeed smaller in `3.1.0` because a lot of functionality has been moved to other modules.
- The download page on our site does not support Maven/Gradle script generation for `3.0.0`. Migrating to `3.1.0` or higher is highly recommended.

**Comment by hyfloac** [comment]
Alright I found where I screwed up, I was calling a runtime dependency for `lwjgl-platform` and not `lwjgl`.

Minor problem with the build script generator I thought I should mention: when you have the `Everything` radio box selected it generates dependency downloads for **Everything**, the problem with this is that some things like `Assimp bindings` aren't enabled and can't be enabled but are still generated, which is a bit of a problem because the reason you can't enable them is they have been removed/don't exist on Maven.

**Comment by apostolos** [comment]
@hyfloac Assimp bindings have just been added to LWJGL so, for the moment, are only available on Nightly builds.

Maybe we should just hide them on other builds to avoid confusion.

**Comment by hyfloac** [comment]
@apostolos My point was the generated build script has errors in them which should be fixed.

**Comment by apostolos** [comment]
@hyfloac You're right, it will be fixed later tonight.

**Comment by apostolos** [comment]
@hyfloac Fixed via [f17639b18e4a6b67c36d5eb9d7491cedf1ed774b](https://github.com/LWJGL/lwjgl3-www/commit/f17639b18e4a6b67c36d5eb9d7491cedf1ed774b)
