### ISSUE TITLE
OpenCL Info util

### ISSUE THREAD

**Issue by gtsiam** [LWJGL/lwjgl3#263]
While trying to get a basic lwjgl OpenCL app working, I. noticed what a real pain it is to get Info from the opencl api. For example, to get a platform's name, you need to reconstruct a string from a byte buffer. So I think a class that could do this could name things a alot more straightforward. And this is already implemented in an InfoUtil class (which is in the source's test folder, for some reason?) 
So, just as a simple channel, could you move that class over to the main part of lwjgl?

**Comment by Spasi** [comment]
LWJGL 2 and early versions of LWJGL 3 had that class as part of LWJGL. The reasons was that, indeed, all the `clGet*Info` functions are error-prone and a pain to use. It was removed before the LWJGL 3.0.0 release, because it was considered overly verbose and against the general lwjgl3 philosophy of keeping things lightweight and close to the original API.  It was also a maintenance issue, because every possible return type of every possible Info function ought to be covered. Note that the current `InfoUtil` class in the LWJGL tests provides methods only for the small subset of information needed by the demos.

With that said, the LWJGL test suite is there for a reason; users are welcome to copy code they need and adjust it to their requirements. It is covered by the same permissive BSD license as the rest of LWJGL. If you add more methods, you're also welcome to contribute it back for other people to use, if you wish so.
