### ISSUE TITLE
Consistent method name casing

### ISSUE THREAD

**Issue by brainscript** [LWJGL/lwjgl3#266]
I really like the fact that LWJGL offers a lot of bindings to various useful libraries,
but there's one thing that drives me crazy: The _**inconsistent casing** of method names_.

Look at the examples.
- :white_check_mark: `glClearColor(...)`
- :white_check_mark: `glfwDefaultWindowHints()`
- :white_check_mark: `alDeleteBuffers(...)`

All of them are `lowerCamelCase` and comply with the Java Conventions. :+1:
They consist of the prefix of the library followed by the name of the actual method.
Awesome, but what about for example STB and Nuklear?
- :confused: `stb_vorbis_open_memory(...)`
- :confused: `nk_label_wrap(...)`

They follow the same general "layout", but in `snake_case`.
Well, I get the point that these are just bindings to C/C++ libraries, but still:
Why not rename the methods? In all the cases I found you can simply split the name by `_` and capitalize all parts except the first one. Then the examples would look like this:
- :white_check_mark: `stbVorbisOpenMemory(...)`
- :white_check_mark: `nkLabelWrap(...)`

What do you think about it?

**Comment by httpdigest** [comment]
I think the goal was never to make the method names consistent with the Java conventions. (it's a mere conincidence that the OpenGL function names comply with that).
The goal has been to have the names identical to their native function names, which LWJGL provides bindings for, so as to simplify porting C/C++ code to LWJGL/Java.

**Comment by Spasi** [comment]
Java conventions are followed for class names only (including struct and callback classes).

The original symbols are used for all constants and functions. This is not an inconsistency in LWJGL, but a deliberate design decision. The idea is that new users looking for tutorials are much more likely to find resources written in native code, rather than in Java/LWJGL. Being able to copy/paste C calls inside your Java code, with minimal porting, is an explicit goal of LWJGL. That's why APIs like OpenGL are completely static, when every other Java library exposes OpenGL via instance methods. It's easier to do that (because of the way GL contexts work), but breaks the aforementioned benefit.

With that said, you're welcome to fork LWJGL and change its generator to do exactly what you propose. It should be trivial, but let me know if you need help with it.

**Comment by brainscript** [comment]
@httpdigest Many developers use LWJGL, because they prefer Java over C (or C++). One (probably trivial sounding) good thing about Java is, that - unlike with other programming languages - developers actually care about coding style and conventions - including casing of `variableNames`, `methodNames` and `CONSTANT_NAMES` (static finals).

Just because the methods I'm talking of are "just" bindings they are still being use **inside** actual Java code and it just makes the code look a lot less clean.

---

@Spasi Mmhh, what about allowing both?
Due to the fact that many developers use static imports to use the methods we could have two classes:
- A "normal" one with no changes to the method names
- A class with a special suffix (like "J" for "Java" or "CC" for "CamelCase")

Developers would be able to decide what they want then:
- Be able to copy-paste C code without renaming the methods
- **OR:** Have a clean code by renaming the methods

**Comment by Spasi** [comment]
I'm afraid being friendly to Java developer aesthetics is not a priority for LWJGL. LWJGL is low level, hard to use, designed for experienced developers that know what they're doing. It's also designed to be easy to wrap in higher-level frameworks and engines (see libGDX etc), which are welcome to expose the functionality in a friendly manner.

Generating twice as many classes is not an option. LWJGL is already massive and complex as it is.

**Comment by brainscript** [comment]
@Spasi Fine, I give up.
