### ISSUE TITLE
Calling GL11.glGenTextures() crashes the entire JVM.

### ISSUE THREAD

**Issue by Coppyhop** [LWJGL/lwjgl3#304]
Hello all, I was starting a new project, my first with the new LWJGL 3. All was going well, however upon trying to load textures I noticed only what I assume is a critical bug. Whenever I call GL11.glGenTextures() the JVM crashes entirely, giving me the hs_err log. I've tried on 2 different computers, different LWJGL versions (the 3.1 release doesn't have OpenGL natives anymore it seems), this has happened on 3.0.0, 3.1.1, and 3.1.2. This happened on 2 different computers running 2 different operating systems, windows and linux. Here is the code I am using that crashes the JVM.

```
import java.io.FileInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.nio.ByteBuffer;

import org.lwjgl.opengl.GL11;

import de.matthiasmann.twl.utils.PNGDecoder;
import de.matthiasmann.twl.utils.PNGDecoder.Format;

public class Loader {

	public Texture loadTexture(String filename){
		
		ByteBuffer buf = null;
		int tWidth = 0;
		int tHeight = 0;
		 
		try {
		    InputStream in = new FileInputStream(filename);
		    PNGDecoder decoder = new PNGDecoder(in);
		    tWidth = decoder.getWidth();
		    tHeight = decoder.getHeight();
		    buf = ByteBuffer.allocateDirect(
		            4 * decoder.getWidth() * decoder.getHeight());
		    decoder.decode(buf, decoder.getWidth() * 4, Format.RGB);
		    buf.flip();
		     
		    in.close();
		    
		    
		} catch (IOException e) {
		    e.printStackTrace();
		    System.exit(-1);
		}
		
		int texId = GL11.glGenTextures();
		GL11.glBindTexture(GL11.GL_TEXTURE_2D, texId);
		GL11.glTexImage2D(GL11.GL_TEXTURE_2D, 0, GL11.GL_RGB, tWidth, tHeight, 0, 
		        GL11.GL_RGB, GL11.GL_UNSIGNED_BYTE, buf);
		GL11.glBindTexture(0, GL11.GL_TEXTURE_2D);
		return new Texture(texId);
		
	}
	
	public Texture testTexture(){
		int texId = GL11.glGenTextures();
		return new Texture(texId);
	}
	
}
```
I also have attached the hs_err logs from both computers here.
[hs_err_linux.zip](https://github.com/LWJGL/lwjgl3/files/974946/hs_err_linux.zip)
[hs_err_windows.zip](https://github.com/LWJGL/lwjgl3/files/974949/hs_err_windows.zip)

**Comment by raniejade** [comment]
@Coppyhop are you calling `loadTexture` from a different thread? This happened to me, I just changed my code to upload the texture in thread owning the OpenGL context.

**Comment by Spasi** [comment]
> siginfo: ExceptionCode=0xc0000005, reading address 0x0000000000000f00

> siginfo: si_signo: 11 (SIGSEGV), si_code: 1 (SEGV_MAPERR), si_addr: 0x0000000000000f00

LWJGL uses a thread-local array of pointers to call OpenGL functions. `f00` is the `glGenTextures` offset in that array. The crashes you're seeing mean that there is no OpenGL context current in the current thread when the function is called (`NULL + f00 == 0x0000000000000f00`).

Users are not expected to know this of course, but another hint is that the crash happens in `lwjgl_opengl.dll/so`, rather than in the OpenGL driver. This can only happen if a) no context is current or b) `lwjgl-opengl.jar` and the corresponding `lwjgl_opengl` shared library come from different LWJGL releases. LWJGL does not do anything in JNI code except forward the call to the native library.

Such application bugs are common and indeed LWJGL does not throw a useful exception in this case. It did in previous releases, but a trade-off has been made; the current implementation prefers optimal performance over debugging utility.

**Comment by AAbhishek1234** [comment]
> @Coppyhop are you calling `loadTexture` from a different thread? This happened to me, I just changed my code to upload the texture in thread owning the OpenGL context.

How exactly did yo do that ??
