### ISSUE TITLE
Debugging Nuklear code?

### ISSUE THREAD

**Issue by dustContributor** [LWJGL/lwjgl3#339]
Hi! Nuklear is driving me nuts. Like 70% of the API is missing docs, so stuff I try either doesn't does what I'm trying to do, or crashes the VM.

Could it be possible to debug Nuklear code? From what I've read it can get pretty complex.

From what I've gathered I'd need to recompile Nuklear with whatever compiler settings LWJGL uses, with debug symbols, then use those compiled libs in the Java program instead of LWJGL-bundled ones (somehow, LD_PRELOAD maybe?), launch it, then attach a debugger to the process from an IDE (I'm guessing I'd be using something like QtCreator or KDevelop).

Is that right? Or is there a simpler way that I'm not seeing?

Probably I could also grab any of the self contained examples in Nuklear's repo and use those as test-bed for what I'll be doing in Java, I guess that could be more practical...

**Comment by kenzierocks** [comment]
If I recall correctly, you can directly specify the absolute path to the library using an system property, which should be easier than LD_PRELOAD.

**Comment by Spasi** [comment]
Indeed, not all Nuklear functions are documented, but the native header contains usage documentation that has not been added to LWJGL yet (PRs welcome).

My recommendation would be:

- Read the usage sections and have a look at the code examples (in `nuklear.h`).
- Play with the [native demos](https://github.com/vurtun/nuklear/tree/master/demo).
- Attach `nuklear.h` to your project and inspect the code when you're having trouble. Most functions are very simple and you can easily figure out if you're doing something wrong.

If you really want to use a debugger, then yes, it should be possible to build `lwjgl_nuklear` with debug symbols. There's no system property for Nuklear that overrides the shared library location, but it shouldn't be a problem. Use either `java.library.path` or `org.lwjgl.librarypath` to point to the folder containing the debug binary and make sure the bundled binary isn't in the classpath (if the SharedLibraryLoader is used). You can use `-Dorg.lwjgl.util.Debug=true` and `-Dorg.lwjgl.util.DebugLoader=true` to verify that the correct one is being loaded.

The compiler options that need to change in order to produce a debug binary are in `config/<platform>/build.xml`, in the "compile" `macrodef`.

**Comment by dustContributor** [comment]
> Read the usage sections and have a look at the code examples (in nuklear.h).
Attach nuklear.h to your project and inspect the code when you're having trouble. Most functions are very simple and you can easily figure out if you're doing something wrong.

Yup that's exactly what I have been doing and as I mentioned, comments just stop happening 1/4 into the sources and after that it's just a stream of not terribly intuitive code where each function depends on an unknown function that has to be called before to use it.

> Play with the native demos.

Yeah, I'll do that first. It involves half of what I'd have to do to get a debugger going (ie, setting up the environment to compile the lib) so I might as well just try that first. Hopefully since it's a single header lib that ought to simplify things.

Do you compile https://github.com/LWJGL/lwjgl3/blob/master/modules/core/src/main/c/nuklear/nuklear.h as-is or are there any defines set anywhere else? There are tons of things that can be #ifdef'd inside Nuklear and I'm not sure which ones LWJGL uses in particular, if any.

> Use either java.library.path or org.lwjgl.librarypath to point to the folder containing the debug binary and make sure the bundled binary isn't in the classpath

Sweet, I'll use that then.

**Comment by Spasi** [comment]
> Do you compile `nuklear.h` as-is or are there any defines set anywhere else? There are tons of things that can be #ifdef'd inside Nuklear and I'm not sure which ones LWJGL uses in particular, if any.

The generated C file that includes `nuklear.h` is [here](https://github.com/LWJGL/lwjgl3-generated/blob/master/c/nuklear/org_lwjgl_nuklear_Nuklear.c).
