### ISSUE TITLE
V-sync problems

### ISSUE THREAD

**Issue by francogp** [LWJGL/lwjgl3#340]
All my monitors work on 60 hz:

### Issue details
- If I use **LWJGL 3.0, 3.1**, coded V-Sync ON (and forced V-Sync on Radeon Drivers), I get **30 FPS** (windowed mode).
- If I use **LWJGL 3.0, 3.1**, coded V-Sync ON (and DISABLED V-Sync on Radeon Drivers), I get **60 FPS** (windowed mode).
- If I use **LWJGL 2.x**, coded V-Sync ON (and forced V-Sync on Radeon Drivers), I get **60 FPS** (windowed mode) as expected on my monitor Hz.
- If I use **LWJGL 2.x**, coded V-Sync ON (and DISABLED V-Sync on Radeon Drivers), I get **60 FPS** (windowed mode)

### Tested on:
Windows 10 + AMD + Forced v-sync on drivers = **30 FPS problem appear**.
Windows 10 + NVIDIA + Forced v-sync on drivers = 60 FPS.
Ubuntu 17.10 + NVIDIA+ Forced v-sync on drivers = 60 FPS.

### Expected results
I should always get 60 FPS as my monitor expect, instead of 30.

_NOTE_: Using latest drivers on all PC up today.

**Comment by Spasi** [comment]
GLFW forces the swap interval to 0 (i.e. vsync disabled) in windowed mode if desktop compositing is enabled on Windows. Instead, it uses [DwmFlush](https://msdn.microsoft.com/en-us/library/windows/desktop/dd389405%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) when `glfwSwapBuffers` is called. [This is](https://github.com/glfw/glfw/commit/8309e0ecb09fe5cf670dff5df1e7ca71821c27bd) the relevant commit.

My guess is that with the AMD driver you sync to a v-blank with `DwmFlush`, then the driver syncs to the next v-blank when `SwapBuffers` is called (because of the forced v-sync setting). This effectively cuts your frame rate in half.
