### ISSUE TITLE
glfwCreateWindow bug in MacOS High Sierra

### ISSUE THREAD

**Issue by ThePerkinrex** [LWJGL/lwjgl3#377]
### Environment

* LWJGL version: `3.1.6` 
* LWJGL build #: `14`
* Java version: `1.8.0_91`
* Platform: `macOS High Sierra (V 10.13.3)`
* Module: `GLFW:glfwCreateWindow()`

### Description

The function glfwCreateWindow just hangs and doesn't return for a very long (haven't seen it end) amount of time. Only happens with the Gradle distribution (Maven not tested), the ZIP distribution works perfectly
This happens on the code from te example at www.lwjgl.org/guide

**Comment by Spasi** [comment]
Cannot reproduce on LWJGL `3.1.6`, Java `1.8.0_161`, macOS `10.13.3`.

Have you set `-XstartOnFirstThread` when running via Gradle?

**Comment by ThePerkinrex** [comment]
Yes, maybe it is IntelliJ idea?

**Comment by sriharshachilakapati** [comment]
@ThePerkinrex Spasi always runs with IntelliJ IDEA, and so do I. That should never be a problem because IntelliJ runs it as a separate process, it is not executed from within the IDE.

I had this kind of issue happened previously, when I run a project stored on a NTFS formatted USB drive from a linux box. It takes around 10 seconds to properly start. However, neither LWJGL nor IntelliJ are responsible for it, as I can see that even a JavaFX program takes the same amount of time to load from that drive. If I just copied the entire project to the local hard disk, it was fast enough like every other application.

I seriously doubt if there is anything wrong with LWJGL in this case. Do you have a kinda similar situation as me?

**Comment by ThePerkinrex** [comment]
@sriharshachilakapati Just tried to recreate it and I couldn't. Only removed another Class with a main() method (I thought it wouldn't be a problem as it wasn't running but obviusly I was wrong)

**Comment by GingerGeek** [comment]
Hi,

I have been struggling with a `glfwCreateWindow` hang as well.
I too am running my application within IntelliJ


After far too much time and effort, I tracked down that macOS had a nice popup hidden away causing the hang
![The last time you opened java, it unexpectedly quit while reopening windows. Do you want to try to reopen its windows again?](https://user-images.githubusercontent.com/4943487/43803774-a823532a-9a91-11e8-9a97-0eb8a30c7336.png)

The `glfwCreateWindow` hangs until the dialogue is acknowledged.

In order to reproduce you have to create a fatal error which forces the JVM to abort execution. Taking the guide as the example removing `glfwMakeContextCurrent(pointer);` and `GL.createCapabilities();` causes `glClearColor(1.0f, 0.0f, 0.0f, 0.0f);` to create such an error:
```
FATAL ERROR in native method: Thread[main,5,main]: No context is current or a function that is not available in the current context was called. The JVM will abort execution.
	at org.lwjgl.opengl.GL11C.glClearColor(Native Method)
	at org.lwjgl.opengl.GL11.glClearColor(GL11.java:1075)
        ...
```
When this happens macOS pops up with this dialogue:
![java quit unexpectedly](https://user-images.githubusercontent.com/4943487/43803999-6fd361c6-9a92-11e8-86ee-6ce1a215805e.png)

From my testing, clicking ignore will still cause the above behaviour where it will hang for user acknowledgement before opening the window.

Hope this helps someone!

**Comment by deerangle2** [comment]
I got this error when I had forgotten LWJGLs `GL.createCapabilites()` before rendering. Add that in and it should work!
