### ISSUE TITLE
Vulkan 1.1 Bindings

### ISSUE THREAD

**Issue by tbotting** [LWJGL/lwjgl3#380]
Hello,

As you've probably heard, Khronos Group has released a new version of Vulkan; 1.1.
I'm wondering if there are any plans on adding support for this.

**Comment by Spasi** [comment]
Yes, of course. The Vulkan bindings are generated with [lwjgl3-vulkangen](https://github.com/LWJGL/lwjgl3-vulkangen), which needs significant updates to properly support Vulkan 1.1. It will take a few days.

There is one non-trivial issue that I'd like feedback on:

A lot of struct types that were previously defined in extensions (usually with the `KHR` suffix), have been promoted to the Vulkan 1.1 core. There are now two such struct types, with and without the suffix. Most (if not all) are identical, the new type is just an alias. The problem is that struct types are mapped to classes in LWJGL, with a significant amount of code in them. The question is, how should this situation be handled in the bindings?

1. Rename the existing classes to drop the suffix, use the new name for both core and extension functionality (assuming no changes have been made during the promotion, other than the name). Obviously, this breaks existing code that uses the extension types.
2. Keep the existing classes and create new ones without the suffix.
3. Like 2, but use inheritance to reuse whatever code can be reused and maybe make the two types compatible. For example, make `VkBindBufferMemoryInfo` extend `VkBindBufferMemoryInfoKHR`, then `VkBindBufferMemoryInfo` can be used with the extension, but `VkBindBufferMemoryInfoKHR` cannot be used with the core functionality. Somewhat cleaner, but also weird.
4. Hybrid: Do 1 for `KHX` (experimental) extensions, 2/3 for other extensions.

Whatever choice is made, it will have to be honored in future Vulkan updates too.

**Comment by tbotting** [comment]
Thanks for your reply and your work on LWJGL! That's a tough question, it would be sweet to not have a lot of duplicate classes. But I can also see people not upgrading LWJGL just because they can't or don't want to fix the renaming of the classes used.

**Comment by elect86** [comment]
First of all, one important thing to know is if all the new `struct`s are identical or less.

Moreover, if I take you example as reference, I can see in the [docs](https://www.khronos.org/registry/vulkan/specs/1.1-khr-extensions/html/vkspec.html#VkBindBufferMemoryInfoKHR) that `VkBindBufferMemoryInfoKHR` is so defined:

`typedef VkBindBufferMemoryInfo VkBindBufferMemoryInfoKHR;`

This is a clear intention of what is primary and what is secondary: `VkBindBufferMemoryInfo` is the primary class name, `VkBindBufferMemoryInfoKHR` is just an alias to smooth the update. 

I'd interpreter this on jvm as: you can also pass a `VkBindBufferMemoryInfoKHR` class where `VkBindBufferMemoryInfo` is expected. In this term, If you want to exploit inheritance, I'd `VkBindBufferMemoryInfoKHR : VkBindBufferMemoryInfo`

If you would like to have exactly the same behavior on jvm as c, you may create a sort of native `nVkBindBufferMemoryInfo` and then have `VkBindBufferMemoryInfoKHR : nVkBindBufferMemoryInfo` and `VkBindBufferMemoryInfo : nVkBindBufferMemoryInfo`. In this way they are exactly interchangeable.

Or simply forget about java and use `typealias` Kotlin.

A couple of observations to do:

- everything that got vk1 is very much likely going to get also vk1.1 
- the more time passes by, the more core `struct`s will be used instead of their extension counterpart (future code is very likely to use core `struct`s)
- it's possible that extensions will be also removed in future versions

Personally, I'd also avoid a duplication, because the huge effort to maintain it and the confusion given by duplication is not worth the advantage of avoiding renaming existent class names.

my 2c
