### ISSUE TITLE
Assimp AIMesh.mTextureCoords incorrect type

### ISSUE THREAD

**Issue by kenzierocks** [LWJGL/lwjgl3#390]
### Environment

* LWJGL version: `3.1.6` 
* LWJGL build #: `14`
* Java version: `1.8`
* Platform: `Linux`
* Module: `assimp`

### Description

It looks like the Assimp `AIMesh` class has the wrong type for `mTextureCoords`. The C code uses ` C_STRUCT aiVector3D*` for both this field and `mVertices`, but `AIMesh` has `PointerBuffer` for `mTextureCoords` instead of `AIVector3D.Buffer`.

**Comment by Spasi** [comment]
The `aiMesh` struct defines `mVertices` and `mTextureCoords` as:

```c
C_STRUCT aiVector3D* mVertices;
C_STRUCT aiVector3D* mTextureCoords[AI_MAX_NUMBER_OF_TEXTURECOORDS];
```

The first is a pointer to an array of `aiVector3D` structs, with length `mNumVertices`.

The second is an array of pointers to arrays of `aiVector3D` structs, with length `AI_MAX_NUMBER_OF_TEXTURECOORDS`. Each element of the array is either `NULL` or points to an array of `aiVector3D` structs, with length `mNumVertices`. This is correctly mapped to a `PointerBuffer`.

The same applies to `mColors`. A mesh can have multiple sets of vertex colors and texture coordinates. E.g. there may be multiple textures applied to a mesh, each with a different set of texture coordinates.

**Comment by kenzierocks** [comment]
That makes sense. However, it's not clear (in LWJGL) that the pointers are to `AIVector3d.Buffer`s. Could this be documented somewhere?

**Comment by Spasi** [comment]
See the [AIMesh javadoc](https://javadoc.lwjgl.org/org/lwjgl/assimp/AIMesh.html). Each member is adequately documented and there's also the C struct layout at the end.

If you're looking for a more fluent and type-safe API, then I'm afraid this is not currently possible (without performance sacrifices). I guess this deserves an explanation.

First of all, LWJGL 3 had a few important goals:

- Be easier to maintain than LWJGL 2.
- Have better performance than LWJGL 2.
- Have more features than LWJGL 2.
- Have bindings that are **source compatible** with LWJGL 2 (as much as practically possible).

These goals were mostly met, but that last point is why the classes `BufferUtils` and `PointerBuffer` are still there in the package root. Refactoring `PointerBuffer` to something better was not an option. Even if it were, Java 8 (our compilation target) does not offer anything interesting.

This is going to change in LWJGL 4, which is going to target whatever Java version first ships with projects Panama & Valhalla. Under the current proposal ([State of the Isthmus v0.3 - May 2018](http://cr.openjdk.java.net/~mcimadamore/panama/panama-binder-v3.html)), instead of a `PointerBuffer`, a member like `mTextureCoords` would be mapped to an:

`Array<Array<AIVector3D>>`

This does look like something that could be done right now, but in that future Java version:

- `AIVector3D` would be a value type (Project Valhalla - value types).
- `Array<AIVector3D>` would be a generic value type, without boxing (Project Valhalla - generic specialization).
- `Array<Array<AIVector3D>>` would be natively supported by the JVM (Project Panama - FFI).

With the above, the API becomes fluent and type-safe, as well as zero-overhead (no boxing, the JVM can use these types directly in native function calls).

**Comment by kenzierocks** [comment]
That sounds exciting! Thanks for the explanation, and I'll look into learning more about C type declarations.
