### ISSUE TITLE
Download doesn't start

### ISSUE THREAD

**Issue by Zamundaaa** [LWJGL/lwjgl3#402]
This is just a minor inconvenience, but it's just annoying to download the full package and pick out the parts I need. Generating the ZIP on https://www.lwjgl.org/customize just doesn't start a download. Tried with Firefox and Chromium on Ubuntu and Firefox on Windows
It shows the page with generating ZIP bundle... but then simply nothing more

**Comment by kenzierocks** [comment]
Works for me with Chrome on Windows. Are you able to save the specific config you're using? Perhaps there's something wrong with what you've chosen.

**Comment by Zamundaaa** [comment]
Yes I am. But github apparently doesn't like json files, so you'll have to rename it back for use... I've tried multiple different selections, too, so that's probably not the issue. Tried Chrome on Windows now, no download either. Also tried on Android now, Firefox and Chromium. Nothing works
[lwjgl-release-custom-zip.txt](https://github.com/LWJGL/lwjgl3/files/2259048/lwjgl-release-custom-zip.txt)

**Comment by TheMrMilchmann** [comment]
The issue is that attempting to fetch JOML from https://build.lwjgl.org/addons/joml/joml-1.9.10.jar yields a `403` error. I assume some "behind-the-scene" step accidentially got skipped in LWJGL/lwjgl3-www#55.

@apostolos Could you please look into this?

@Zamundaaa In the meantime you could exclude JOML from your ZIP bundle and download it manually from maven central (http://central.maven.org/maven2/org/joml/joml/1.9.10/).

**Comment by Spasi** [comment]
Thanks @TheMrMilchmann, JOML `1.9.10` should now be available.
