### ISSUE TITLE
can STBTruetype in LWJGL3 render Chinese words?

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#417]
I see your demo file TruetypeOversample and get a little knowledge about how to render text using it.
My question here is , is there some way to render Chinese words?
I guess so , but I just don't know how to achieve it.
Can you put a demo about it? Or, can you show me where can I find such knowledge?
Thanks.
     --XenoAmess

**Comment by Spasi** [comment]
Yes, with a few changes<sup>1</sup> you could render Chinese text in the `TruetypeOversample` sample, but it's not a practical solution for real-world applications. The problem is that you'd need a massive texture<sup>2</sup> to store all chinese glyphs. It requires lots of memory and packing the glyphs with stb_truetype and uploading the data to the GPU would cause a substantial delay to the application startup.

Rendering Chinese, and other languages with lots of glyphs, usually requires a caching scheme for efficiency. I.e. you pack only the glyphs currently/recently visible on screen, rather than every possible glyph. This is not implemented in any LWJGL demo, but you should be able to find more information elsewhere.

<sup>1</sup> I was able to render (google-translated) Chinese by doing the following:

- Changed the bitmap dimensions from `512 x 512` to `16k x 16k`. If your GPU does not support such a big texture, you could drop it to `8k x 8k` and also reduce the font sizes in the `scale` array (or use a single size instead of two).
- Changed the font from `FireSans` to a font that contains Chinese glyphs. On Windows 10, `C:/Windows/Fonts/simsun.ttc` worked fine.
- Changed the packing/rendering code to work with around `37000` glyphs instead of only `128`.

<sup>2</sup> To check if the glyph packing is working correctly, add `stbi_write_bmp("font_texture.bmp", BITMAP_W, BITMAP_H, 1, bitmap)` after the `stbtt_PackEnd(pc)` call, then open the generated bitmap in your favorite image viewer.

**Comment by XenoAmess** [comment]
Yes you are right.
It can do this way , but cost me 300MB memory and 10 seconds or so to load one ttf on my PC.
I get a SSD, 6700K, 1060, and 24GB DDR4, so I guess it can be far slower on some older machine.
But it is still acceptable.
By the way, a caching scheme for efficiency is better, but we have to figure out what characters are offen used and what not, and pick them one by one. I choose not to do this. Just, let it load.
Another way is to get it dynamic. Do not load the ttf totally from the beginning, but when use a char,we set a flag, and load it. And next time we see this flag on, then just use it.
But I'm afraid the check itself can have a cost in performance too.
Also, load one char seems far slower than load many chars in one time.
Anyway, I will try to find a better way to achieve this, but I'm just use the primitive way for now.
I really appreciate your precious help.
Thank you.
--XenoAmess
