### ISSUE TITLE
Make the demos more readable

### ISSUE THREAD

**Issue by Shryne** [LWJGL/lwjgl3#440]
I am currently looking at the stb demos and I am especially talking about these classes:  
[EasyFont.java](https://github.com/LWJGL/lwjgl3/blob/18975883e844d9dc53874836ec45257da13085d9/modules/samples/src/test/java/org/lwjgl/demo/stb/EasyFont.java)  
[FontDemo.java](https://github.com/LWJGL/lwjgl3/blob/18975883e844d9dc53874836ec45257da13085d9/modules/samples/src/test/java/org/lwjgl/demo/stb/FontDemo.java)  
[Truetype.java](https://github.com/LWJGL/lwjgl3/blob/18975883e844d9dc53874836ec45257da13085d9/modules/samples/src/test/java/org/lwjgl/demo/stb/Truetype.java)  
It's unnecessarily difficult to understand these examples and they should be refactored to make it easier for new people to use the library. These are some of the issues I found:  
- Inheritance: Since EasyFont inherits from FontDemo in a very strange way, one has to keep both files open and jump back and forth between them to follow the control flow  
- Multiple files: There are some imports from other demo classes that aren't even inside of the stb package (like GLFWUtil)  
- Multi imports for everything: If the user (like me) has a lwjgl version that doesn't have every used class in the demo, it won't be possible to see the missing class  
- Almost no comments  
- Too many features per demo making the demo classes bigger than necessary  

I think the demos should be self-contained and small to offer a minimal example. Every demo that needs multiple files should get its own project (or at least a whole package for itself).

**Comment by httpdigest** [comment]
The purpose of such demos/examples/tests is not to teach people about that library (or the bindings to the library) or to make those tests particularly readable, but rather to validate the basic functionality of the binding (such as to avoid regression when updating the library to a new version).
It's not in the scope of the LWJGL project to provide tutorial/guide-like demos to all the external libraries LWJGL provides bindings for.

**Comment by Shryne** [comment]
Ok, but shouldn't a regression test be readable, too? For example reducing the jumping would raise the maintainability and some statements about the expected behaviour would add some value, too.

**Comment by dustContributor** [comment]
I get what you mean and I particularly dislike demos/showcases/examples that basically do their own little library of utility functions to do stuff so you end up having to do the double work of figuring out the framework **and** the "demo framework" built around the examples (Vert.x I'm looking at you very, very angrily).

That being said, I think the idea is that to learn to actually use the library, you go to the library's documentation and examples, not LWJGL's. Since the whole thing about LWJGL is to provide the most thin binding possible so the knowledge about the original library is directly transferable.

That's why when people ask "How do I learn to use LWJGL's OpenGL?" we direct them to learn to use OpenGL itself, since that's pretty much it (+/- MemoryUtil and friends).

Moreover, a lot of those demos are direct ports of their original counterparts in each library's repo. So often if you're looking at them and wondering why the weird naming scheme for instance, that's most certainly because it was directly ported from the original library examples.

Although in this case (stb) it seems those examples were coded by Spasi from scratch.
