### ISSUE TITLE
SSE

### ISSUE THREAD

**Issue by TheSeraphProject** [LWJGL/lwjgl3#455]
Hi, so I wanted to get started using the SSE module for LWJGL3 but ran into an issue with it.
Everything provided by the `SSE` and `SSE3` classes in the `org.lwjgl.util.simd` package is rarely mentioned in SSE examples.
Rather they use commands like `_mm_set_ps`, `_mm_add_ps` etc.
So I went to look at the lwjgl samples, forums, issues, and wasn't able to find anything about the SSE module anywhere.
Is the module complete or is it a placeholder for when it does get added in it's entirety?
If I'm missing something please feel free to point out, as I mentioned above, I was trying to get started with it and have no previous experience with SSE commands.

Kind regards,
Seraph

**Comment by kenzierocks** [comment]
I don't think the module is intended to let you use the SSE instructions, since the overhead incurred by switching to native would be much higher than doing the raw instructions. It looks like it's just to configure some float-related settings. 

I would watch [JEP 338](http://openjdk.java.net/jeps/338) for SSE-related instructions in Java.

**Comment by TheSeraphProject** [comment]
Ah alright, I will definitely check that out.
Thank you for your quick response. @kenzierocks
