### ISSUE TITLE
suggestion : add annotation @MainThreadOnly on all functions who can only run on main thread.

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#474]

**Comment by TheMrMilchmann** [comment]
What is the purpose of this? These requirements are (or should be) documented anyway for all relevant methods. The only benefit I can think of right now is that someone could write IDE plugins or agents that attempt to check whether the calling thread is valid.

(This is actually be implemented in [LWJGLX/debug](https://github.com/LWJGLX/debug) using a hand-written lookup.)

**Comment by XenoAmess** [comment]
@TheMrMilchmann purpose：for debugging my event processing framework. (to see if it wrongly give a MainThreadOnlyEvent to a non-mainthread.)
and for auto generating the annotation to all my funtions using any of functions with this annotation. 
And for creating logs.

**Comment by Spasi** [comment]
The main thread limitation is something that applies to GLFW functions, which is just one LWJGL binding among many. It'd be weird to add an annotation to the API just for that.

All GLFW functions include a note in their javadoc that says whether the main thread limitation applies or not. Suggestion: assume that every GLFW function must only be called from the main thread, except a (much shorter) set of functions that may be called from any thread. It should be simple to compile such a set from the [GLFW](https://github.com/LWJGL/lwjgl3/blob/master/modules/lwjgl/glfw/src/generated/java/org/lwjgl/glfw/GLFW.java) source code and use it in your framework (lookup by function name instead of checking an annotation).

**Comment by XenoAmess** [comment]
@Spasi Ok，that make sense.

**Comment by httpdigest** [comment]
For debugging such issues, you can use LWJGLX/debug. It will tell you about threading issues with GLFW and also about OpenGL issues.
