### ISSUE TITLE
Exception in main about LWJGL

### ISSUE THREAD

**Issue by DanielCoreOfficial** [LWJGL/lwjgl3#485]
### Environment

* LWJGL version: `3.2.2` 
* LWJGL build #: `10`
* Java version: `JSE-11`
* Platform: `macOS`
* Module: `core|binding name`

### Description

Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW
	at main.Main.main(Main.java:10)
Caused by: java.lang.ClassNotFoundException: org.lwjgl.glfw.GLFW
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
No errors or nothing, this is all that appears towards me.

**Comment by Spasi** [comment]
It looks like GLFW is missing from the class/module-path.

**Comment by DanielCoreOfficial** [comment]
> It looks like GLFW is missing from the class/module-path.

Got it working! How do you run -XStartFromOnThread with JVM? Is it a Build Configuration with the VM?

**Comment by RainerYuan** [comment]
> > It looks like GLFW is missing from the class/module-path.
> 
> Got it working! How do you run -XStartFromOnThread with JVM? Is it a Build Configuration with the VM?

Can I ask how did you resolve this issue. I'm getting the same thing

**Comment by Crytoma** [comment]
Make sure to add any natives that you are using to the JRE Native library location.

**Comment by Fearaniar** [comment]
What command should I put into the VM-arguments then (assuming that's the JRE Native library location?). I have a linux machine--I'm not sure if that changes things?

**Comment by httpdigest** [comment]
The original issue discussed here was `Exception in thread "main" java.lang.NoClassDefFoundError: org/lwjgl/glfw/GLFW` which means that the classpath/modulepath is missing the GLFW jar from LWJGL 3. So, you have to put it into the classpath or modulepath. However, LWJGL 3's GitHub issues are not the best way to learn about basic Java tooling. You need to consult other places for that. Simply google for "how to run java with jar in classpath/modulepath" or the likes.

**Comment by Fearaniar** [comment]
I have experience with integrating JavaFX with the Eclipse IDE. For that to work, I had to download the JavaFX-15 .jar files, and set up a user library with them. Then, I would have to go into the build path for the current project and add that library to the project. As that alone is not enough, I would then need--for each independent class--to update the VM arguments with this command:

--module-path "path/to/javafx-15/lib" --add-modules javafx.controls,javafx.fxml

As without it, anything I wrote refused to run.

-----

I admit I'm not as savvy with programming as I would like to be, but I have decent reasoning, and I assumed the process mentioned above would be similar to making LWJGL work on the Eclipse IDE. I have added--what I believe to be--the necessary LWJGL 3 .jar files into a user library and set those into the classpath/modulepath; and have added nearly a dozen different VM arguments referencing the natives, and anything concerning GLFW, but nothing has worked so far.

I've spent several days trying to make this work; I wouldn't be here if I couldn't figure anything else out...

I have:
OS: Ubuntu 20.04 (Linux)
Java: OpenJDK-14
Eclipse IDE: 4.14
LWJGL: 3.2.3

**Comment by httpdigest** [comment]
Yes, I understand and this may all well be.
However, *nothing* of this is related to or specific to LWJGL.
You would have the *exact same* problems with any other library. And I assume you do not open an issue tickert with _every_ other third party library that you use and that you did not properly integrate into your Java runtime classpath/modulepath?
So again: Look (possibly at Oracle documentation) how to _properly_ configure the Java classpath (or modulepath - whichever you use) and then consult the Eclipse IDE documentation on how to configure that there.

**Comment by httpdigest** [comment]
If you are not that experienced with the Java tooling, i.e. with the Java module system, which I also **do not recommend** to people not familiar with it - instead stick to the classpath, then simply follow along this article:

https://github.com/LWJGL/lwjgl3-wiki/wiki/1.2.-Install#eclipse

**As mentioned in there, the absolute simplest way to setup LWJGL 3 is with Maven.**
I repeat: **Use Maven! It is by far the simplest way to setup an initial project with LWJGL 3!**
Eclipse is equipped with everything needed for this.
You just say Eclipse to configure your project as a Maven project, then go to https://lwjgl.org/customize , switch to "Maven" mode and select the libraries you want and then copy/paste the snippet into your pom.xml and it **will work out of the box** immediately **without any** manual JVM argument configuration.

Just make sure whenever Eclipse asks you about any "module" that it wants to create, that you say **NO**.
Otherwise, you are using the module system and need to properly configure the LWJGL module dependencies in your module-info.java.
