### ISSUE TITLE
[Question] does memUTF8 only support codepoints smaller than 65536?

### ISSUE THREAD

**Issue by Masy** [LWJGL/lwjgl3#486]
According to the wikipedia page of UTF-8, the format supports codepoints up to 0x10FFFF. The char will then use up 4 bytes. Codepoints from 0x800 to 0xFFFF will use up 3 bytes. When encoding a char with the MemoryUtil method, bits greater than 0xFFFF are ignored though.

Examples:
0x0000 will use 1 byte
0x0080 will use 2 bytes
0xFFFF will use 3 bytes
0x10000 should use 4 bytes, but will use 1 byte
0x10080 should use 4 bytes, but will use 2 bytes
0x1FFFF should use 4 bytes, but will use 3 bytes

Is this an error in LWJGL or is it meant to only support characters up to 0xFFFF?

Edit: Or is this even an error due to the fact that java chars are encoded with UTF-16?

**Comment by Spasi** [comment]
The `char` type in Java is a 16-bit unsigned integer, so it cannot represent values higher than `0xFFFF`. Java strings are UTF-16 encoded, which is a variable length encoding scheme, like UTF-8. Codepoints up to `0xFFFF` are represented as a single `char`, while characters above `0xFFFF` are represented as two `char` values. The two values are called surrogates and together they make a surrogate pair. To go from UTF-16 to UTF-8, you must iterate the string codepoints, not its chars, then encode each codepoint to the appropriate UTF-8 representation.

The `MemoryUtil` methods should do this correctly, unless you've got some code that demonstrates otherwise. Example verification code:

```java
MemoryStack stack = stackPush();
for (int cp = 0; cp <= 0x10FFFF; cp++) {
    char[] chars = Character.toChars(cp);
    if (chars.length == 1 && (Character.isHighSurrogate(chars[0]) || Character.isLowSurrogate(chars[0]))) {
        continue;
    }
    String string = new String(chars);

    byte[] java = string.getBytes(StandardCharsets.UTF_8);

    try (MemoryStack frame = stack.push()) {
        ByteBuffer lwjgl = frame.UTF8(string, false);

        assertEquals(lwjgl.remaining(), java.length);
        for (int j = 0; j < java.length; j++) {
            assertEquals(lwjgl.get(j), java[j]);
        }

        String decoded = memUTF8(lwjgl);
        assertEquals(decoded, string);
    }
}
```

Note that the LWJGL implementation is tuned for performance and does not handle illegal or incomplete surrogate pairs, it assumes that strings contain well-formed UTF-16.

**Comment by Masy** [comment]
Ok thanks. But I casted the codepoint int to a char and then used String.valueOf([char]) to write the codepoint into the bytebuffer, shouldn't this work correctly then?
