### ISSUE TITLE
How do you add text in LWJGL3?

### ISSUE THREAD

**Issue by JavasPichu** [LWJGL/lwjgl3#489]
Been wondering this for a while but even researching it, due to Slick-util being discontinued I believe? I don't know how to draw fonts or labels and such, I tried using F21Builder yet the majority of the time the tutorials I've seen isn't really what I'm curious about.

Any links or any videos that could've helped me?
Thank you!

**Comment by XenoAmess** [comment]
I just learned it from 

[demo](https://github.com/LWJGL/lwjgl3/blob/2359eb7b5a9e7e629beae95d3cdab8e997c59039/modules/samples/src/test/java/org/lwjgl/demo/stb/Truetype.java)

The code is neat there and it is easy to change a small lines to add your own logic.
The only thing must taken care of is that you might have to make BITMAP_W and BITMAP_H several times larger if you are dealing with Korean, Japanese or Chinese or other language which have far more chars.

**Comment by joafalves** [comment]
If still interested, please check the font implementation I'm using on my framework. Its a bit more complex than the ones you can find on the lwjgl examples due to batching/shaders operations.

Generating font data and textures:
https://github.com/joafalves/pixel/blob/develop/modules/core/src/main/java/pixel/content/Font.java

Usage example (using a glyph/texture batcher):
https://github.com/joafalves/pixel/blob/develop/modules/examples/src/main/java/pixel/examples/simple/SpriteBatchFontGame.java
