### ISSUE TITLE
Add imgui or other UI to LWJGL

### ISSUE THREAD

**Issue by ejamshidiasl** [LWJGL/lwjgl3#507]
Hello
i want to add UI to GLFW window.
in c++ i achieve this with ImGui but there is no working ImGui for LWJGL (kotlingraphics dead)
i saw nuklear and some others but they are too complex.
so how to add ImGui to LWJGL?

**Comment by Sylvyrfysh** [comment]
Kotlin graphics isn't dead. Myself and Elect have University and a job
respectively, so it isn't our primary focus. However, it will receive
updates, especially if you create an issue with either a missing feature,
request, or bug, we will work to resolve it as fast as possible (see
kotlin-graphics/imgui#99, where an issue happened yesterday and we have
responded). Please give it a try and let us know if it's not up to your
standards!

**Comment by ejamshidiasl** [comment]
i want to use with LWJGL.is there any tutorial or sample?

why a bad word written in kotlin graphics repository?

**Comment by Sylvyrfysh** [comment]
There is a sample in the imgui-gl folder.

The commit history has been amended to remove the offending word.

**Comment by elect86** [comment]
> Hello
> i want to add UI to GLFW window.
> in c++ i achieve this with ImGui but there is no working ImGui for LWJGL (kotlingraphics dead)
> i saw nuklear and some others but they are too complex.
> so how to add ImGui to LWJGL?

Well, it depends by your definition of dead. 

If it is dead whenever it doesnt get any commit in the last couple of days, then it might be dead multiple times.

Otherwise for me it's pretty active: of all those repo only bullet and ovr are archived.

All the rest is a pretty large portion of sw to play with.

> i want to use with LWJGL.is there any tutorial or sample?

Follow the readme, its name shall also be self-inviting

> why a bad word written in kotlin graphics repository?

Because sometimes when you code, you get so frustrated and passionate that you swear
