### ISSUE TITLE
memAlloc(int), nmemAlloc(long), why?

### ISSUE THREAD

**Issue by XenoAmess** [LWJGL/lwjgl3#509]
I just wonder why MemoryUtil.memAlloc(int size) do not receive a long as MemoryUtil.nmemAlloc(long size).

**Comment by kenzierocks** [comment]
You need to allocate a single block of memory larger than 1.5GB? That would be the only reason.

If you're wondering why it doesn't have a native (`n`) variant, it's because it doesn't need one. The native version would be the same signature.

**Comment by TheMrMilchmann** [comment]
`java.nio.ByteBuffer` (and the like) make use of `int`-based indexing [1], thus a buffer with a capacity larger than `Integer.MAX_SIZE` would be partially unadressable at best but possibly even erroneous. Until the API is extended or changed [2] (e.g. to use `long` for indices) it does not make sense to support wrapping a large buffer `via ByteBuffer`.

However, if you want to use larger buffers you should be able to allocate one via [nmemAlloc](https://javadoc.lwjgl.org/org/lwjgl/system/MemoryUtil.html#nmemAlloc(long)). All of the functionality required to work with such a buffer is available in `org.lwjgl.system.MemoryUtil` (e.g. [memPut*](https://javadoc.lwjgl.org/org/lwjgl/system/MemoryUtil.html#memPutByte(long,byte)) and [memGet*](https://javadoc.lwjgl.org/org/lwjgl/system/MemoryUtil.html#memGetByte(long))).

[1] https://docs.oracle.com/en/java/javase/13/docs/api/java.base/java/nio/ByteBuffer.html#get(int)
[2] https://bugs.openjdk.java.net/browse/JDK-8180628

**Comment by Spasi** [comment]
That's correct, LWJGL uses `int` for size/index when an API has anything to do with NIO buffers. `long` is used in the `n` prefixed methods because that's what the native API supports and could be useful to advanced users.

LWJGL 4 will adopt Project Panama and (hopefully) all interactions with NIO will be eliminated. So, a method like `memAlloc` would accept a `long`, or even a `size_t` inline type (see Project Valhalla).

Btw, there's another difference between `BufferUtils` and `MemoryUtil` allocation methods:

- In `BufferUtils`, everything has to go through `ByteBuffer.allocateDirect`. For example, allocating a `DoubleBuffer` means allocating a `ByteBuffer` first, i.e. `ByteBuffer.allocateDirect(capacity).asDoubleBuffer()`. But that limits the maximum `DoubleBuffer` capacity by the maximum `ByteBuffer` capacity (2GB) and you can't have a `DoubleBuffer` with `Integer.MAX_VALUE` elements.

- In `MemoryUtil`, buffers are allocated directly via `Unsafe` and the `Integer.MAX_VALUE` limit applies equally to all buffer types. So, if you wanted to, you could allocate a 16GB `DoubleBuffer` and address it just fine with the standard NIO accessor methods (the `int` index is converted correctly to a `long` address internally).
