### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by deeprobin** [LWJGL/lwjgl3#567]

**Comment by octylFractal** [comment]
This request makes no sense -- this projects entire purpose is to be a "LightWeight **Java** GameLibrary" (LWJGL!), having the produced product in Rust would defeat the entire point.

**Comment by apostolos** [comment]
Out of scope

**Comment by XenoAmess** [comment]
@deeprobin 
You CAN open a repo named lwrgl instead.
But that is another story.
And seems nobody here are interested in.

**Comment by deeprobin** [comment]
There is C/C++ code which could be rewritten in rust. Rust has many advantages

**Comment by XenoAmess** [comment]
> There is C/C++ code which could be rewritten in rust. Rust has many advantages

Would it have equal or even better performance after the rewrite?

**Comment by deeprobin** [comment]
@XenoAmess It varies from project to project. However, Rust is largely memory-safe and uses the ownership system instead of reference counting.

And it has often been proven that Rust projects are faster than C/C++ projects - even if it's only a few milliseconds, it certainly makes a difference with an OpenGL wrapper.

[Benchmark: Rust vs C](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust.html)
[Benchmark: Rust vs Clang](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust-clang.html)
[Benchmark: Rust vs C++](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust-gpp.html)
[Benchmark: Rust vs Go](https://benchmarksgame-team.pages.debian.net/benchmarksgame/fastest/rust-go.html)

**Comment by XenoAmess** [comment]
@deeprobin Sorry but as far as I know this repo has no guys familiar with rust, especially using rust with jni...
And that seems not a easy work to migrate the codes now to rust, as there be so many codes.
If you really want to do this, I guess you can:
1. ask about @Spasi .
2. fork this repo and rewrite one native module to rust version.
3. build dlls.
4. write tests for showing it really faster than the older dll used.
(you can do this using jmh or something else).
But, as this be a big change, we might better ask @Spasi first.

**Comment by TheMrMilchmann** [comment]
There seems to be some confusion here, so let's clarify a couple of things:

> There is C/C++ code that could be rewritten in rust. Rust has many advantages

There is some C and C++ code in this repository since some modules contain the code of the respective projects. They are kept in sync with the upstreams whenever the bindings are updated (with a few minor fixes for LWJGL interop on top in some cases). Porting those third-party projects to Rust is obviously out of scope for this project.

Additionally, LWJGL generates C files that are needed for JNI. Those are very simple wrappers that bridge Java code and native libraries. Porting those to Rust is extremely unlikely to yield any advantage since they are auto-generated anyway, a C API is required for JNI, and (I assume) the Rust compiler can't properly validate JNI stuff which would void Rust's additional safety features and optimizations.

> If you really want to do this, I guess you can:
    2. fork this repo and rewrite one of the native modules to rust version.

A rewrite of one of the native modules should not be submitted to LWJGL. It would either need to be maintained as a fork of the upstream project or submitted and integrated into the upstream project. However, if you really want to go down this road, for LWJGL to work, the project would probably need to expose a C API anyway. (In fact, if you port the implementation of a library to Rust but keep the same C API, LWJGL might already be able to load the library.)

**Comment by XenoAmess** [comment]
> Those are very simple wrappers that bridge Java code and native libraries. Porting those to Rust is extremely unlikely to yield any advantage since they are auto-generated anyway,

Yes, this is the reason why I doubt about if the rewrite can increase performance.

> a C API is required for JNI,

At least I don't know anything about how to use rust in jni, and I don't think any guys in this repo do...

> In fact, if you port the implementation of a library to Rust but keep the same C API, LWJGL might already be able to load the library.

Yes.
And even if he changed something, I guess he might only need to rewrite the modules named ***-native-*** .
And if he change it with care, then it can still work perfectly with other original modules from lwjgl.
Just, at least in theory.

**Comment by RUSshy** [comment]
that benchmark is stupid, it's basically LLVM(clang) vs GCC, pointless

**Comment by XenoAmess** [comment]
> that benchmark is stupid, it's basically LLVM(clang) vs GCC, pointless

I always not trust any benchmarks.
I'd prefer test it in real situation.
Or, at least, using jmh to test how it goes after it get built.
