### ISSUE TITLE
Update to OpenGL 4.6

### ISSUE THREAD

**Issue by jredfox** [LWJGL/lwjgl3#574]
According to open gl the latest version is 4.6 your on 4.5

lwjgl version:
https://www.lwjgl.org/

opengl current version:
https://www.khronos.org/registry/OpenGL/index_gl.php

**Comment by httpdigest** [comment]
I guess what you are trying to say is that the lwjgl.org web page in the "Main Features" section unter OpenGL where it says "LWJGL supports all OpenGL versions (including the latest 4.5 specification)" does not advertize LWJGL supporting the latest OpenGL 4.6 version.
However, LWJGL has been supporting OpenGL 4.6 since mid-2017.
It's just that the web page does not properly advertize this.
You probably want to issue a PR to https://github.com/LWJGL/lwjgl3-www to correct this.

**Comment by jredfox** [comment]
O well then it's a website issue please fix it
