### ISSUE TITLE
freetype & harfbuzz binding

### ISSUE THREAD

**Issue by NekoCaffeine** [LWJGL/lwjgl3#611]
Hi, I'd like to request an [freetype](https://www.freetype.org) & [harfbuzz](https://github.com/harfbuzz/harfbuzz) binding.

Describe why you need it and how you're going to use it.
I am trying to implement glyph rendering, but I realized that not all languages are as simple as common ones (just rendering from left to right). Some minor languages require the use of scripts in the font to calculate the layout.

Why harfbuzz and not ICU Layout engine.
https://openjdk.java.net/projects/harfbuzz/
https://openjdk.java.net/jeps/258

Related Resources:
https://www.freetype.org/developer.html#source-code
https://harfbuzz.github.io/
https://harfbuzz.github.io/ch12.html

A simple shaping example:
https://harfbuzz.github.io/ch03s03.html

**Comment by Spasi** [comment]
Hey,

I've started working on this and the first step was setting up CI builds for harfbuzz & freetype. They're up...

https://github.com/LWJGL-CI/harfbuzz/actions
https://github.com/LWJGL-CI/freetype/actions

...but not without issues:

- I could not get freetype to build on Windows ARM64.
- Both have a bunch of dependencies that, either I could not get to build, or they would build on certain platforms/architectures and not on others. In the end I disabled everything so that there's (missing) feature parity.
- Of those dependencies, the weirdest one is that harfbuzz depends on freetype (helper functions in the `hb-ft.h` header) and freetype depends on harfbuzz (for improved auto-hinting). I wasted too much time on breaking this cycle and failed, so both features are disabled. I'm not sure how important this is (helper functions could be implemented manually? auto-hinting does not matter if harfbuzz is used directly?).

I would really appreciate any contributions towards fixing the above (especially the first one). Contact me on the LWJGL discord server (https://discord.gg/yuKsaEguzj) if you need to discuss details.

**Comment by mkalinowski2** [comment]
Hey @Spasi I prepared CI/CD for compiling harfbuzz and freetype on all platforms, I hope that it'll help :)

https://github.com/LWJGL-CI/freetype/pull/1

**Comment by Spasi** [comment]
LWJGL `3.2.2-snapshot+8` is now available with FreeType and HarfBuzz bindings.

- The FreeType native binaries include HarfBuzz and export its full API.
- The default harfbuzz module natives are standalone, without the FreeType helper functions.
- To enable FreeType/HarfBuzz interop, use one of the following:
    * launch the JVM with `-Dorg.lwjgl.harfbuzz.libname=freetype`
    * run `Configuration.HARFBUZZ_LIBRARY_NAME.set("freetype")`
    * run `Configuration.HARFBUZZ_LIBRARY_NAME.set(FreeType.getLibrary())` - recommended
- With the above, the HarfBuzz bindings will use FreeType's shared library instead and the `org.lwjgl.harfbuzz.natives-*` module is not required.

Please report any issues with the FreeType/HarfBuzz interop. Also, any sample/demo contributions would be very welcome.

**Comment by ws909** [comment]
@Spasi Will this remain the default behaviour? Judging by the number of git updates seen in mkalinowski’s PR, it seems like you struggled a bit getting it all working together, so I’m unsure if you’re looking to change the current behaviour.

**Comment by Spasi** [comment]
@ws909 Indeed, it was a nightmare to get it working, especially making it have zero outside dependencies. I don't have a reason to change the above behavior, but I'm not going to use it either. If users think otherwise, please let me know.

One objective I have with the shared library loading mechanism in LWJGL is to allow advanced users replace LWJGL's native binaries with their own builds. There are a number of reasons they might want to do so. Right now, both FreeType and HarfBuzz bindings can be used independently and custom binaries will work. Only the "hacky" override described above is LWJGL specific, that's why it is optional by default.

I updated `lwjgl3-www` this morning, you should be able to see FreeType now.
