### ISSUE TITLE
Ctrl+click on Mac (laptop with touchpad) is not detected as right-click

### ISSUE THREAD

**Issue by MarcinSc** [LWJGL/lwjgl3#621]
### Environment
* LWJGL version: `3.2.3` 
* LWJGL build #: `?`
* Java version: `11.0.7`
* Platform: `macOS`
* Module: `?`

### Description
When using libGDX with LWJGL3 dependency, ctrl+click on Mac (laptop with touchpad) is not detected as right-click, instead it's a left-click. This is a recommended way of achieving right-click on Mac:
https://support.apple.com/en-gb/guide/mac-help/mh35853/mac

This worked fine on the "legacy" libGDX that used LWJGL 2.9.3.

Here is the issue raised on libGDX project:
https://github.com/libgdx/libgdx/issues/6405

**Comment by httpdigest** [comment]
LWJGL 3 simply exposes GLFW, which libGDX is probably using on desktop with LWJGL 3 for windowing and mouse input handling. LWJGL 3 itself does not and probably will not intercept and interpret any window messages. LWJGL 2 _did_ do this, because it implemented input handling itself, whereas LWJGL 3 simply exposes the GLFW API to the client application and expects it to handle window/input messages/events accordingly. You might probably want to raise the issue on https://github.com/glfw/glfw instead.
