### ISSUE TITLE
Improve or remove support for maven (both code and documentation)

### ISSUE THREAD

**Issue by kukel** [LWJGL/lwjgl3#652]
### Environment

* LWJGL version: from older ones (at least) up to `3.2.3/4` (master)
* LWJGL build #: n/a
* Java version: n/a
* Platform: all
* Module: all

### Description

Please correct the maven pom so everything works OR remove it and also remove it from the documentation. Similar to 
[#367](Port Eclipse project to the new directory layout)

**Comment by TheMrMilchmann** [comment]
In case you're referring to the `pom.xml` in the root directory: This is a dummy file to enable [GitHub's dependency graph](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph) feature. (See 7cf825fd378dd561018636d1bfa56669b0c9a3d7)

LWJGL currently uses Ant to build and the [build process](https://github.com/LWJGL/lwjgl3/tree/master/doc#installation) is thoroughly documented. There is an open issue (#16) about **moving** the build to Gradle (which is currently only used for publishing) but (as far as I know) there is no intention to support multiple build systems since this introduces significant maintenance cost without any real benefit.

With all of this said, keep in mind that this is only relevant for people who want to develop LWJGL itself. It doesn't affect users of the library in any way. If you just want to use LWJGL as a library, you should just follow the [Getting Started](https://www.lwjgl.org/guide) guide.


(On a side note: #367 would probably be solved by #16 too since most Java IDEs can import Gradle projects. I've tried to tackle it several times in the past with unsatisfying results but I didn't give up on it.)

**Comment by XenoAmess** [comment]
> In case you're referring to the `pom.xml` in the root directory: This is a dummy file to enable [GitHub's dependency graph](https://docs.github.com/en/code-security/supply-chain-security/understanding-your-software-supply-chain/about-the-dependency-graph) feature. (See [7cf825f](https://github.com/LWJGL/lwjgl3/commit/7cf825fd378dd561018636d1bfa56669b0c9a3d7))
> 
> LWJGL currently uses Ant to build and the [build process](https://github.com/LWJGL/lwjgl3/tree/master/doc#installation) is thoroughly documented. There is an open issue (#16) about **moving** the build to Gradle (which is currently only used for publishing) but (as far as I know) there is no intention to support multiple build systems since this introduces significant maintenance cost without any real benefit.
> 
> With all of this said, keep in mind that this is only relevant for people who want to develop LWJGL itself. It doesn't affect users of the library in any way. If you just want to use LWJGL as a library, you should just follow the [Getting Started](https://www.lwjgl.org/guide) guide.
> 
> (On a side note: #367 would probably be solved by #16 too since most Java IDEs can import Gradle projects. I've tried to tackle it several times in the past with unsatisfying results but I didn't give up on it.)

@TheMrMilchmann 
why moving to gradle, but not to maven?

**Comment by httpdigest** [comment]
Hi @kukel and welcome to LWJGL!
Glad that you enoy using LWJGL and want to participate in improving it.

> ... and also remove it [Maven] from the documentation

Can you pinpoint the exact location (with quote/reference) where you think that the pom.xml/Maven setup of the LWJGL/lwjgl3 project itself is referenced? I can't find any. What you probably seem to refer to is the paragraph:

> The build configurator generates Maven & Gradle declarations that can be added to existing projects. This is the easiest way to use LWJGL while developing.

[in the README.md](https://github.com/LWJGL/lwjgl3/blob/master/README.md#getting-started). That however does not refer to the project's own [pom.xml file](https://github.com/LWJGL/lwjgl3/blob/master/pom.xml) but to the Maven pom.xml (and also Gradle build.gradle) snippet that you can generate via https://www.lwjgl.org/customize to copy/paste a pom.xml or build.gradle snippet into your own build to have a declaration of all necessary dependencies for the modules that you selected in the build customizer.
