### ISSUE TITLE
Vulkan Module does not support creating multiple queus from one family

### ISSUE THREAD

**Issue by GalaxyCo** [LWJGL/lwjgl3#657]
### Description

The Vulkan Binding VkDeviceQueueCreateInfo does not support to set the value queueCount,  this makes it impossible to submit to multiple queues from multiple threads,

Something along the lines of this : 

```
VkDeviceQueueCreateInfo queueCreateInfo{};
queueCreateInfo.queueCount = 2; //this is always one in the current binding
```
(c++ example)

should be possible

thanks for your time :)

### Environment

* LWJGL version: 3.2.3 
* LWJGL build: 13
* Java version: 14
* Platform: Windows
* Module: org.lwjgl.vulkan.VkDeviceQueueCreateInfo

**Comment by httpdigest** [comment]
The queue count is implicitly set by the `.remaining()` of the FloatBuffer you specify for `pQueuePriorities`. Since the spec _requires_ you to set the queue priorities ([not setting them is invalid according to the spec](https://www.khronos.org/registry/vulkan/specs/1.2-extensions/man/html/VkDeviceQueueCreateInfo.html#VUID-VkDeviceQueueCreateInfo-pQueuePriorities-parameter)) the cound is taken from that buffer.remaining().

**Comment by GalaxyCo** [comment]
ok thank you for the quick reply
