### ISSUE TITLE
Improve SPIRV bindings

### ISSUE THREAD

**Issue by tlf30** [LWJGL/lwjgl3#712]
### Description

Hello,
The bindings for SPIRV are clunky, and a bit unsafe. 

For example, a simple snippet to use reflections to list uniforms:
```java
//Get metadata from shader
try (MemoryStack stack = MemoryStack.stackPush()) {
    System.err.println("Creating spvc context");
    PointerBuffer contextPointer = stack.mallocPointer(1);
    Spvc.spvc_context_create(contextPointer);
    Spvc.spvc_context_set_error_callback(contextPointer.get(0), (userdata, error) -> {
        String errorString = MemoryUtil.memUTF8(error);
        LOGGER.severe("SPIR-V Error: " + errorString);
    }, 0L);

    System.err.println("Parsing spirv");
    IntBuffer words = spvBuffer.asIntBuffer();
    PointerBuffer ir = stack.callocPointer(1);
    Spvc.spvc_context_parse_spirv(contextPointer.get(0), words, words.limit(), ir);

    System.err.println("Creating compiler");
    PointerBuffer compilerPointer = stack.mallocPointer(1);
    Spvc.spvc_context_create_compiler(contextPointer.get(0), Spvc.SPVC_BACKEND_GLSL, ir.get(0), Spvc.SPVC_CAPTURE_MODE_TAKE_OWNERSHIP, compilerPointer);

    System.err.println("Creating shader resource");
    PointerBuffer resourcesPointer = stack.mallocPointer(1);
    Spvc.spvc_compiler_create_shader_resources(compilerPointer.get(0), resourcesPointer);

    System.err.println("Getting shader resources");
    PointerBuffer listPointer = stack.mallocPointer(1);
    PointerBuffer sizePointer = stack.mallocPointer(1);
    Spvc.spvc_resources_get_resource_list_for_type(resourcesPointer.get(0), Spvc.SPVC_RESOURCE_TYPE_UNIFORM_BUFFER, listPointer, sizePointer);

    System.err.println("Wrapping resources");
    int size = (int) sizePointer.get(0);
    System.err.println("Size = " + size);
    SpvcReflectedResource.Buffer resources = SpvcReflectedResource.createSafe(listPointer.get(0), size);

    System.err.println("Shader uniforms:");
    for (int i = 0; i < size; i++) {
        SpvcReflectedResource resource = resources.get(i);
        int set = Spvc.spvc_compiler_get_decoration(compilerPointer.get(0), resource.id(), Spv.SpvDecorationDescriptorSet);
        int binding = Spvc.spvc_compiler_get_decoration(compilerPointer.get(0), resource.id(), Spv.SpvDecorationBinding);

        System.err.println("Uniform: " + resource.nameString());
        System.err.println("ID: " + resource.id());
        System.err.println("Set = " + set);
        System.err.println("Binding = " + binding);
    }

    System.err.println("Destroying spvc context");
    Spvc.spvc_context_destroy(contextPointer.get(0));
}
```

First, to get the error string on the callback, a memory map has to be made to a pointer that was passed to us:
```java
 Spvc.spvc_context_set_error_callback(contextPointer.get(0), (userdata, error) -> {
        String errorString = MemoryUtil.memUTF8(error); <--- Manually getting the string from a pointer 
        LOGGER.severe("SPIR-V Error: " + errorString);
    }, 0L);
```

Next, when getting the shader resources, the size is returned as a pointerbuffer, when in fact it should be an intbuffer as the value is directly the size:
```java
 System.err.println("Getting shader resources");
    PointerBuffer listPointer = stack.mallocPointer(1);
    PointerBuffer sizePointer = stack.mallocPointer(1);  <--- This holds the actual number of returned resources, not the pointer to an int.
    Spvc.spvc_resources_get_resource_list_for_type(resourcesPointer.get(0), Spvc.SPVC_RESOURCE_TYPE_UNIFORM_BUFFER, listPointer, sizePointer);
```

Last as far as this example goes, the pointer to the list of resources has to manually be mapped to the `SpvcReflectedResource.Buffer`.
```java
 System.err.println("Wrapping resources");
    int size = (int) sizePointer.get(0);
    System.err.println("Size = " + size);
    SpvcReflectedResource.Buffer resources = SpvcReflectedResource.createSafe(listPointer.get(0), size);
```

This is just a quick example snippet from an application of mine, but it clearly demonstrates some of the unsafe behaviors of the SPIRV binding. 
Looking at other bindings such as the Shaderc binding, many of these things are handled internally in the binding providing the user a safer API. 

Thoughts?

Thanks,
Trevor

EDIT: I would also like to add to this that the current javadocs are missing the SPV module.

**Comment by Spasi** [comment]
Hey @tlf30,

> First, to get the error string on the callback, a memory map has to be made to a pointer that was passed to us:

Upcalls in LWJGL are intentionally low-level/unsafe because that's the most lightweight option available. We have the luxury of method overloads with downcalls (unsafe method with the `n` prefix + normal method + other overloads for convenience), but upcalls always need to be directed to a single method. JNI callbacks are already seriously expensive and I didn't want to force even more performance overhead to every user of a given callback. For example, getting a `String` in the callback would mean always parsing for the null-terminating character and allocating a Java `String` instance. Some users may want to do something else with the string pointer or not care about it at all (I mean in general, not talking about `spvc_context_set_error_callback` specifically).

> Next, when getting the shader resources, the size is returned as a pointerbuffer, when in fact it should be an intbuffer as the value is directly the size

The `resource_size` parameter has a type of `size_t *`, which is a pointer to an `int` on 32-bit processes and a `long` on 64-bit processes. Mapping it to a `PointerBuffer` is correct.

> Last as far as this example goes, the pointer to the list of resources has to manually be mapped to the SpvcReflectedResource.Buffer.

Java doesn't have output parameters and the only other option would be making struct classes mutable (i.e. making it possible to change the address they point to). It would lead to a lot of confusing code imho.

> it clearly demonstrates some of the unsafe behaviors of the SPIRV binding.
Looking at other bindings such as the Shaderc binding, many of these things are handled internally in the binding providing the user a safer API.

LWJGL bindings are as safe or unsafe as the underlying library being exposed to the Java land. This is what "Lightweight" means in LWJGL. Anything else would mean too much work for the maintainers (to implement, explain, support and so on). We are all Java developers, we know how to trivially wrap the unsafe-ness in clean, safe APIs.

> EDIT: I would also like to add to this that the current javadocs are missing the SPV module.

The SPVC C header contains no documentation atm, there was nothing to create javadoc from.

**Comment by tlf30** [comment]
Thank you for the detailed reply. I took the time to investigate how the SPIRV-Cross library was built. Unfortunately, it seems to be a little strange in places, such as returning a `size_t` just to return a count. 

> LWJGL bindings are as safe or unsafe as the underlying library being exposed to the Java land. This is what "Lightweight" means in LWJGL. Anything else would mean too much work for the maintainers (to implement, explain, support and so on). We are all Java developers, we know how to trivially wrap the unsafe-ness in clean, safe APIs.

I see exactly what you mean now. The SPIRV-Cross library itself is a bit cumbersome and exposes raw pointers. Perhaps this is a side effect of creating the C api as a wrapper around the C+ api. It definitely is a big difference after using other libraries that come over quite nice such as shaderc. 

Thank you for all your hard work on this, I feel at the moment this is perhaps as good as it is going to get unless the underlying SPIRV-Cross API changes.
