### ISSUE TITLE
[LMDB] Access fields of MDB_txn structure

### ISSUE THREAD

**Issue by kenwenzel** [LWJGL/lwjgl3#722]
### Description

I need access to the field [MDB_txn::mt_next_pgno](http://www.lmdb.tech/doc/group__internal.html#aa805ac6e787ed14ffd131964638901bc) for implementing an autogrow functionality that dynamically adapts the map size for LMDB.

Is it possible to add this functionality to the LMDB binding?

**Comment by Spasi** [comment]
Hey @kenwenzel,

`MDB_txn` is already exposed in the API as an opaque handle, changing it to a struct would break existing code. We could create a separate struct type and use like `MDBTxn.create(txn).mt_next_pgno()`, where `txn` is the opaque `MDB_txn *` (mapped to `long` in the API). But I'd like to avoid this, the presence of that struct may make users think they should be accessing `MDB_txn` internals, when they normally need/should not.

Since you're trying to access internal state and it's only one member, I would recommend simply using `memGetAddress(txn + 2 * POINTER_SIZE)`. If you need more members and the offset calculation becomes tricky, then please post again and I'll add the new struct type.

**Comment by kenwenzel** [comment]
Thank you for the quick response. I will go with your proposal and directly access the respective memory location.
