### ISSUE TITLE
Binding for libmdbx

### ISSUE THREAD

**Issue by kenwenzel** [LWJGL/lwjgl3#724]
### Library

libmdbx

### Project page

https://erthink.github.io/libmdbx/

### Source repository

https://github.com/erthink/libmdbx

### Platforms

Linux x64, Linux arm64, macOS x64, macOS arm64, Windows x64, Windows arm64

### Description

libmdbx could be a replacement for LMDB with support for automatic size management:
https://erthink.github.io/libmdbx/group__c__settings.html#ga79065e4f3c5fb2ad37a52b59224d583e

The binding should support the same platforms as the LMDB binding.

**Comment by SWinxy** [comment]
Looks like a solid library. It seems to have an extensive C API, which is great (because LWJGL can't do C++ bindings).

**Comment by kenwenzel** [comment]
Does LWJGL have some facility to generate the Kotlin configurations (or at least some stubs) from C header files?

**Comment by kappaOne** [comment]
just curious, instead of another library and binding, why not just increase the maximum LMDB database size instead?

I understand the default is LMDB database limit is 10mb, you could just make it 1GB or higher. It doesn't mean the LMDB database file will immediately be the full size limit, but grow automatically as needed (up to the limit).

**Comment by kenwenzel** [comment]
Yes, that is possible but one has to estimate the db size upfront. It is also a problem under Windows that the db file directly occupies the maximum size. But I've found a way to implement autogrow functionality by using fine-grained read-write-locks in combination with an additional transaction log. (see RDF4J issue above)
