### ISSUE TITLE
OpenGL 4.6 to support apple devices

### ISSUE THREAD

**Issue by jredfox** [LWJGL/lwjgl3#727]
### Description

mac has depreciated opengl since 4.1 and moved to metal. We need you guys to come up with a fix for it on macOs, IPadOs, IOS. If you guys don't fix this for macOs at the very least all java games won't work with mac devices. This means there will be no point to ever use opengl again because no it's limited to only windows and linux. Game developers don't normally manually support linux if they have to convert it to opengl or opengl es graphics api. therefore they will just use direct x 12 and metal.

it needs to be regular opengl and not opengl es there is a cap of profile compatibility contexts and even plain out graphics api behavior like piping, and matrices I believe (push / pop?).

**Comment by jredfox** [comment]
macOs and all apple devices are removing native support for opengl. So you guys need to re-add the drivers and api yourself

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows

**Comment by TheMrMilchmann** [comment]
> mac has depreciated opengl since 4.1 and moved to metal.

Apple deprecated OpenGL support in macOS Mojave 10.14 (in 2018). OpenGL 4.1 was (and still remains) the latest OpenGL version that is natively supported in macOS. While they clearly want us to use Metal, there is no indication that support for this version will be removed in the near future.

> We need you guys to come up with a fix for it on macOs, IPadOs, IOS.

Java and (therefore) LWJGL do not really support iOS and IPadOS due to platform limitations.

> If you guys don't fix this for macOs at the very least all java games won't work with mac devices. This means there will be no point to ever use opengl again because no it's limited to only windows and linux. Game developers don't normally manually support linux if they have to convert it to opengl or opengl es graphics api. therefore they will just use direct x 12 and metal.

If you want to develop a cross-platform application going forward, the best strategy is using Vulkan natively for Windows and Linux, and via MoltenVK (a Vulkan over Metal wrapper) for macOS.

> it needs to be regular opengl and not opengl es there is a cap of profile compatibility contexts and even plain out graphics api behavior like piping, and matrices I believe (push / pop?).

I'm not sure what you mean here.


Generally, it is out of scope for LWJGL to provide **native** OpenGL 4.6 support for macOS. However, it is possible that in the future a library similar to MoltenVK will be distributed alongside LWJGL to provide support for later OpenGL versions. This is tracked in https://github.com/LWJGL/lwjgl3/issues/718.
