### ISSUE TITLE
'Safe' wrappers for more Vulkan types?

### ISSUE THREAD

**Issue by tlf30** [LWJGL/lwjgl3#747]
### Description

Hello @Spasi,
I was wondering why some vulkan types have 'safe' wrappers, such as `VkDevice` or `VkInstance` but others do not, such as `VkDescriptorPool`. 

I would be incredibly useful to have wrappers for these types in order to ensure type safety at the java layer. Right now only having the type safety for some types and not other can get confusing, and make developing memory 'safe' libraries for vulkan difficult.

Second question, would it be possible to make the 'safe' wrappers be instantiated without the create info? There are instances where native libraries pass a pointer to things like the `VkDevice` but then it is impossible to use many of the built in LWJGL functions and I am forced to use the non-safe versions of the function because all I have is the pointer and it is not possible to create a new instance of the `VkDevice` wrapper without the create info, which may not be available. 

Thank you for all your hard work on LWJGL!
I look forward to your response.
~Trevor

**Comment by httpdigest** [comment]
> I was wondering why some vulkan types have 'safe' wrappers, such as VkDevice or VkInstance but others do not, such as VkDescriptorPool

The reason why the five Vulkan types `VkInstance`, `VkPhysicalDevice`, `VkDevice`, `VkQueue` and `VkCommandBuffer` are represented as Java classes instead of simply as a long value is that these five types are what the Vulkan specification calls "dispatchable object handles".

Unlike OpenGL, Vulkan has no notion of a thread-local storage to hold any kind of "context", so dispatchable object handles are used in all Vulkan calls to... well... dispatch Vulkan API calls over in order for the Vulkan runtime/driver and any potential layer to correctly associate these calls with the respective Vulkan instance, device, etc. and any additional per-instance, per-device state they would like to hold.

One such state that LWJGL decides to associate with these is function pointers/addresses and the cached/queried availability of instance and device extensions. The combination of function addresses and extension availabilities is what LWJGL holds in `VkCapabilitiesInstance` and `VkCapabilitiesDevice`, because Vulkan function pointers and enabled extensions are per-instance and per-device within that instance.

So, while in OpenGL, the capabilities can be associated with a thread-local storage, in Vulkan they are associated with these dispatchable object handles. And that's why LWJGL has classes for these five Vulkan types.

While dispatchable handle types are guaranteed to produce a unique value everytime a new object of that type is created, other Vulkan types like `VkDescriptorPool` or `VkSampler` are "non-dispatchable object handles" and _may_ produce identical values (for example, when you create a `VkSampler` with identical settings/properties). Thus, you cannot directly associate state with these values and by design, Vulkan thinks that this should also not be necessary.

**Comment by Spasi** [comment]
Hey @tlf30,

> would be incredibly useful to have wrappers for these types in order to ensure type safety at the java layer

This will never happen in LWGL 3, which has been designed to work efficiently in a Java 8 world. Wrapping opaque handles/pointers would be great for type safety, but the GC overhead would be unacceptable. We'll have to be patient for LWJGL 4, which will require Panama Foreign and Valhalla, then all such handles will become value/primitive types (= zero overhead + type safety).

> would it be possible to make the 'safe' wrappers be instantiated without the create info

A constructor for `VkDevice` that accepts `VKCapabilitiesDevice` instead of `VkDeviceCreateInfo` could be added. But then, `VKCapabilitiesDevice` does not have a public constructor, so not sure how useful that would be.

> There are instances where native libraries pass a pointer to things like the `VkDevice`

Could you explain this use-case a bit more? Which native libraries? Do you have the same problem with `VkInstance`?
