### ISSUE TITLE
glfwCreateWindow creates fullscreen window without monitor parameter when using DECORATED=FALSE

### ISSUE THREAD

**Issue by hoinshembl** [LWJGL/lwjgl3#75]
Even though I am using NULL as the monitor parameter, glfwCreateWindow creates (what I assume is) a fullscreen window. This happens when the width and height are set to the exact resolution as the primary monitor, as well as the position is set to 0,0. Changing the resolution or position by even one pixel doesn't create this issue.

My code is basically the example provided on the LWJGL homepage, along with glfwWindowHint(GLFW_DECORATED, GL_FALSE); (to create a borderless window)
and width and height set to monitor resolution (1920*1080).

The fact that a fullscreen window is created can be observed by a very annoying and noticable black flicker on all monitors when the window looses/gains focus (this doesn't happen when changing one of the values mentioned above by even 1 pixel).

As a side note, my primary monitor is on the left, so 0,0 is the top left corner. Setting the position to 1920/0 (so it perfectly fills the second monitor) doesn't create this issue.

**Comment by httpdigest** [comment]
Can confirm that. Win7 x64, latest LWJGL3 head, msvc 2013 build.
However, it seems that the current glfw head (which I know LWJGL3 does not use) does not exhibit this behaviour anymore (tested with a simple native app).

**Comment by hoinshembl** [comment]
The problem is still present for me in the nightly build (along with the stable/release ofc). I am also running Win7 x64.

**Comment by hoinshembl** [comment]
thanks, i guess I'll just leave the issue open until a newer glfw version is used

**Comment by Spasi** [comment]
I see this on my machine too (Windows 8.1, AMD GPU). It's an [open issue](https://github.com/glfw/glfw/issues/527) in GLFW.

> However, it seems that the current glfw head (which I know LWJGL3 does not use) does not exhibit this behaviour anymore (tested with a simple native app).

You may have done something different, because LWJGL 3 uses the [GLFW head](https://github.com/LWJGL-CI/glfw/commits/master-linux64) (the master-linux64 branch is also used for the Windows builds).

**Comment by httpdigest** [comment]
> You may have done something different, because LWJGL 3 uses the GLFW head (the master-linux64 branch is also used for the Windows builds).

Oh, I thought you switched to some last GLFW release, because of some keyboard issues. But anyhow, now that I tried it again, the flicker is gone with both lwjgl and glfw-native solutions... the only thing remaining is the taskbar getting hidden when going fullscreen, whereas when offsetting the window position by (1, 0), the taskbar remains visible. This seems to be an indicator, too, that GLFW is going fullscreen there.

**Comment by Spasi** [comment]
> Oh, I thought you switched to some last GLFW release, because of some keyboard issues.

Yeah, thought about doing that, but the current head has many important fixes for issues I didn't want LWJGL users to deal with. I'm currently [patching](https://github.com/LWJGL-CI/glfw/commit/8691f8f7cde9ce1210240c519e036297b494f095) the head to fix the keyboard issue on Linux. Also submitted a PR to GLFW but it hasn't been accepted.
