### ISSUE TITLE
Inconsistent Vulkan Struct Buffer Count's

### ISSUE THREAD

**Issue by ewoudje** [LWJGL/lwjgl3#764]
### Question

The LWJGL bindings of Vulkan structs, have field setters sometimes missing but sometimes it does have it; and sometimes it automatically sets the count of said field to the correct limit of the buffer but at other times it does not.

~~And it has as far as I noticed no correlation if the count field is accessible or not.~~, I stand corrected, I couldn't find a example where it does have a modifiable count and is automatically assigned. But its still very inconvenient that it _sometimes_ is  automatically and sometimes not.

As far as I saw there was not yet an issue made for it?

Ex.
When it doesn't do it automatically: VkSubpassDescription#pColorAttachments & colorAttachmentCount
Or VkSubmitInfo#pWaitSemaphores vs VkSubmitInfo#pSignalSemaphores (only one is automatic)

**Comment by octylFractal** [comment]
If you had searched, you would have found my issue filed a while ago regarding this: https://github.com/LWJGL/lwjgl3/issues/539

**Comment by ewoudje** [comment]
But this isn't the only class that is like this? _And I did search but not with colorAttachmentCount but just with count..._

**Comment by httpdigest** [comment]
There is no dedicated count setter when its value would otherwise be _exactly_ implied by spec from the size of another buffer, in order to avoid errors where you would set a count value for a buffer that has less values. That's it.
So, whenever you find a count setter, then it is because there _could_ be situations where you have a different count than the remaining() of one or two buffers in that struct.

**Comment by ewoudje** [comment]
I see, wouldn't it be handier then that it is the remainder until stated otherwise? that you provide a setter and you use it after the buffer? Then I should close this since it is said in https://github.com/LWJGL/lwjgl3/issues/539 that it will be kept this way?
