### ISSUE TITLE
Assimp: Missing ability to read KHR_draco encoded meshes

### ISSUE THREAD

**Issue by hYdos** [LWJGL/lwjgl3#773]
### Version

3.3.2 (nightly)

### Platform

Windows x64

### JDK

Temurin 18

### Module

Assimp

### Bug description

When trying to read a GLTFv2 model which has been exported with draco compression through blender, I'm unable to read it. This seems to be an issue with a feature not being defined in Assimp during the compilation of bindings.
[Assimp glTF2Asset.inl](https://github.com/assimp/assimp/blob/42adc8235479ee96ef22d781d03e65944a9267e2/code/AssetLib/glTF2/glTF2Asset.inl#L1922)

### Stacktrace or crash log output

```shell
`GLTF: Draco mesh compression not supported.`
```

**Comment by DJtheRedstoner** [comment]
Assimp only enables draco support if the [`ASSIMP_BUILD_DRACO` cmake option](https://github.com/assimp/assimp/blob/master/Build.md#cmake-build-options) is set. Otherwise it will just return [that error](https://github.com/assimp/assimp/blob/530ae2b192339a3ad9bf816b7d21c12391658351/code/AssetLib/glTF2/glTF2Asset.inl#L1919-L1924). Enabling that cmake build option should fix this issue, provided it still compiles correctly on all platforms.

**Comment by Spasi** [comment]
Hey @hYdos,

The latest snapshot (3.3.2 build 2) includes Draco support in Assimp.
