### ISSUE TITLE
VkShaderModuleCreateInfo.pCode should probably use IntBuffers instead of ByteBuffers

### ISSUE THREAD

**Issue by theagentd** [LWJGL/lwjgl3#865]
### Version

3.3.2 (nightly)

### Platform

Linux x64, Linux arm64, Linux arm32, macOS x64, macOS arm64, Windows x64, Windows x86, Windows arm64

### JDK

Zulu 17, but irrelevant

### Module

Vulkan

### Bug description

VkShaderModuleCreateInfo.pCode is defined as a uint32_t* in the Vulkan specification. As such, it should be set with an IntBuffer. Note that codeSize is indeed the size in **bytes**, not uint32_t words.

AFAIK, the passed in SPIR-V code itself is based on uint32_t words, and therefore has to have the correct endianness. If you compile your code on a little-endian CPU, dump the SPIR-V contents of the ByteBuffer to disk, then load that data in on a big-endian CPU, it will not work. Taking in an IntBuffer signals that this endianness is important.

I realize that this is quite nitpicking and low-priority, but I wanted to make a report about it nonetheless. :)

**Comment by Spasi** [comment]
Hey @theagentd,

Even though the Vulkan bindings are auto-generated, `VkShaderModuleCreateInfo::pCode` is mapped to `ByteBuffer` with an explicit override. IIRC, the reason was to better support the `VK_NV_glsl_shader` extension, which enables plain GLSL code in `VkShaderModuleCreateInfo`.

This extension is now deprecated so I will probably revert the type to `IntBuffer` in LWJGL 4. `VkShaderModuleCreateInfo` is too commonly used to break compatibility in LWJGL 3. Besides, it's trivial to "cast" a SPIR-V buffer with `MemoryUtil::memByteBuffer(IntBuffer)`

**Comment by theagentd** [comment]
Thanks for the explanation, Spasi! That's a completely understandable reason!
