### ISSUE TITLE
why does opengl load both the binding and opengl32 

### ISSUE THREAD

**Issue by Danjhop4** [LWJGL/lwjgl3#904]
### Question

does the native bindings need opengl32.dil I can’t find a direct reference but it loads both that confused me I thought it was a bug opengl32 was loaded 
Thanks spasi you done a good job by the way
I only know basic java and no native code

**Comment by Spasi** [comment]
If you build LWJGL locally and run `ant demo -Dclass=org.lwjgl.demo.glfw.Gears -Djvmargs="-Dorg.lwjgl.util.Debug=true -Dorg.lwjgl.util.DebugLoader=true"`, you'll see the following:

```
[LWJGL] Loading JNI library: lwjgl_opengl
        Module: org.lwjgl.opengl
        Loaded from classpath: D:\PROJECTS\lwjgl3\bin\libs\native\windows\x64\org\lwjgl\opengl\lwjgl_opengl.dll
[LWJGL] Loading library: opengl32
        Module: org.lwjgl.opengl
        Loaded from system paths: C:\Windows\SYSTEM32\opengl32.dll
```

Both libraries are necessary for the OpenGL bindings to work.

The second library is straightforward: it's the OpenGL library provided by the operating system, the one actually exposing the OpenGL API. You can think of it as your GPU's OpenGL driver (there is some indirection going on, but you can ignore all that).

The first library is a typical JNI library. It provides the implementation for every `native` method inside the OpenGL module. For example, for this Java method:

```java
public static native long nglGetString(int name);

@Nullable
@NativeType("GLubyte const *")
public static String glGetString(@NativeType("GLenum") int name) {
    long __result = nglGetString(name);
    return memUTF8Safe(__result);
}
```

the native code for `nglGetString` lives in the `lwjgl_opengl` native library:

```c
JNIEXPORT jlong JNICALL Java_org_lwjgl_opengl_GL11C_nglGetString(JNIEnv *__env, jclass clazz, jint name) {
    glGetStringPROC glGetString = (glGetStringPROC)tlsGetFunction(111);
    UNUSED_PARAM(clazz)
    return (jlong)glGetString(name);
}
```

Most LWJGL bindings do not need a second native library to work. OpenGL and OpenGL ES are special, because OpenGL contexts (and their corresponding function pointers) are thread-local. Different threads may have to call different functions. In order to expose a static API (OpenGL code in Java that looks the same as the corresponding C code), a thread-local lookup has to happen somewhere. This is what the `tlsGetFunction` does. The details are complicated (see `ThreadLocalUtil` if interested), but this particular implementation is more efficient than doing the thread-local lookup in Java.

LWJGL 4 will migrate to Project Panama and since that's a huge API breaking change, it will be a good opportunity to refactor the OpenGL bindings with a non-static API, similar to JOGL. For example:

```java
// instead of
private String lwjgl3() {
    return glGetString(GL_VERSION);
}

// you'd write
private String lwjgl4(GL gl) {
    return gl.GetString(GL_VERSION);
}
```

It has the drawback that you'll have to pass the OpenGL context around, but it eliminates all thread-local issues.

**Comment by Danjhop4** [comment]
Thanks thought it was something like that the bindings needed opengl32
