### ISSUE TITLE
version string mix up

### ISSUE THREAD

**Issue by limeygopher** [LWJGL/lwjgl3#96]
I'm trying to use OpenGLES 2.0 on a linux box, and the parser chokes on the version string.
I'm running Debian 8, and it has an Intel 945 chipset.

`glxinfo|grep version` gives me:
>server glx version string: 1.4
>client glx version string: 1.4
>GLX version: 1.4
>OpenGL version string: 2.1 Mesa 10.3.2
>OpenGL shading language version string: 1.20
>OpenGL ES profile version string: OpenGL ES 2.0 Mesa 10.3.2
>OpenGL ES profile shading language version string: OpenGL ES GLSL ES 1.0.16

I have a snippet
```java
import org.lwjgl.glfw.GLFW;
import org.lwjgl.opengles.GLES;
import org.lwjgl.system.MemoryUtil;

public class Main {
	public static void main(String[] args) {
		GLFW.glfwInit();
		GLFW.glfwMakeContextCurrent(
			GLFW.glfwCreateWindow(400, 300, "Test", MemoryUtil.NULL, MemoryUtil.NULL));
		GLES.createCapabilities();
	}
}
```

and running it results in
>Exception in thread "main" java.lang.IllegalArgumentException: Malformed API version string [2.1 Mesa 10.3.2]
>    at org.lwjgl.system.APIUtil.apiParseVersion(APIUtil.java:120)
>    at org.lwjgl.opengles.GLES.createCapabilities(GLES.java:218)
>    at Main.main(Main.java:10)

So it seems to try to parse the OpenGL version, not the OpenGL ES one.
When I shortcircuit the prefix checking in APIUtil.apiParseVersion() I can use OpenGL ES 2.0 functions just fine.

**Comment by Spasi** [comment]
Hmm. First of all are you using a GLFW build that supports EGL/OpenGL ES? The build that comes with LWJGL works with desktop OpenGL only. This will change in GLFW 3.2 and you'll be able to select the [context API at runtime](https://github.com/glfw/glfw/issues/145).

If you're using the default LWJGL distribution, then what happens is that GLFW creates a desktop OpenGL context, but LWJGL assumes it's an OpenGL ES context. It works if you fix the API version detection likely because all GLES 2.0 functions are also present in the OpenGL context.

**Comment by limeygopher** [comment]
So I've just revealed how ignorant I am.
I'm using the latest nighlty build (46) and the libglfw in it. After adding the hints GLFW_CLIENT_API, GLFW_CONTEXT_VERSION_MAJOR, and GLFW_CONTEXT_VERSION_MINOR to the window, all seems to be fine, and I don't have to hack anything.
Thanks for your time.
