### ISSUE TITLE
[MacOS] does not render while resizing

### ISSUE THREAD

**Issue by mirraj2** [LWJGL/lwjgl3#975]
### Version

3.3.3

### Platform

macOS arm64

### JDK

JDK 11

### Module

GLFW

### Bug description

On MacOS, I am dragging the window and it does not render at all until I release the mouse button on the drag.  I would like it to keep rendering during the drag operation.

**Comment by octylFractal** [comment]
This looks like the same issue as https://github.com/glfw/glfw/issues/408 -- is that correct?

**Comment by mirraj2** [comment]
that does look similar but not quite the same.  In that issue's screenshot I see artifacts during the drag operation but on my computer I see no artifacts.  

Also that issue seems to be closed without any kind of fix or solution

**Comment by octylFractal** [comment]
The solution is described in https://github.com/glfw/glfw/issues/408#issuecomment-68645440 -- use the window refresh callback <https://javadoc.lwjgl.org/org/lwjgl/glfw/GLFW.html#glfwSetWindowRefreshCallback(long,org.lwjgl.glfw.GLFWWindowRefreshCallbackI)>

**Comment by Spasi** [comment]
Hey @mirraj2, this can be fixed by decoupling event handling and rendering. Event handling is done on the main thread, with blocking `glfwWaitEvents`, while rendering is done continuously on a secondary thread.

See the [Vorbis](https://github.com/LWJGL/lwjgl3/blob/master/modules/samples/src/test/java/org/lwjgl/demo/stb/Vorbis.java) sample for example code. It works nicely on Windows too.

**Comment by mirraj2** [comment]
thank you both!
