### ISSUE TITLE
Typing ERROR Contributed to Can't build

### ISSUE THREAD

**Issue by yuxiangll** [LWJGL/lwjgl3#997]
### Version

3.3.4

### Platform

macOS arm64

### JDK

Zulu OpenJDK 21.0.4

### Module

LWJGL Croe

### Bug description

![7ee1b65029bf65abfb792e48883c8c54](https://github.com/user-attachments/assets/79983f22-fdfb-4a6f-b160-91fb132d7ca0)
You Typed double ":" ,and one ":" is enough
 on the official website download

**Comment by TheMrMilchmann** [comment]
Hi @yuxiangll,
Without more information, I won't be able to comment on the error you were having.
However, the snippet in question is correct:

The string notation for dependencies looks roughly like this:

    <group>:<artifact>(:<version>(:<classifier>)?)?

We don't need to declare the versions for the individual dependencies because they are resolved from the BOM platform dependency. However, the dependencies for the native artifacts use classifiers for the different supported platforms. Thus, to include the correct natives dependency, we **must** declare the classifier, but we can still omit the version by simply using the empty string instead of a version number. This effectively leaves us with the syntax:

    <group>:<artifact>::<classifier>

If still believe, you were facing an error related to this issue specifically, please provide us with more information (such as a stacktrace, logs, and, ideally, an [MCVE](https://stackoverflow.com/help/minimal-reproducible-example)).
